// Keep the AI connection files versioned so GitHub Pages never reuses an
// outdated browser-cached endpoint after a deployment.
import { CONFIG } from "./config.js?v=20260718-ollama";
import { renderScheduleWorkspace } from "./schedules.js?v=20260722-clean-copy";
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, browserSessionPersistence, setPersistence, onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { getDatabase, ref, get, set, push, onValue, runTransaction, remove } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js";

const app = initializeApp(CONFIG.firebase);
const auth = getAuth(app);
const db = getDatabase(app);
const $ = selector => document.querySelector(selector);
const state = { user:null, demo:false, page:"employees", employees:[], entities:["الإدارة العامة","فرع العاصمة","فرع الأحمدي"], settings:{companyLogoUrl:"",companyLogoDataUrl:""}, leaves:[], attendance:{}, schedules:{}, fingerprintPlaces:[], attendanceFilter:null, search:"", pendingLogin:null, bound:false, draftSegments:[], profileEmployeeId:null, sessionExpired:false };
let attendanceRenderTimer=null;

const icons = {
  employees:"<svg viewBox='0 0 24 24'><path d='M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75'/></svg>",
  schedules:"<svg viewBox='0 0 24 24'><path d='M3 5h18v16H3zM16 3v4M8 3v4M3 10h18'/></svg>",
  attendance:"<svg viewBox='0 0 24 24'><circle cx='12' cy='12' r='9'/><path d='M12 7v5l3 2'/></svg>",
  decisions:"<svg viewBox='0 0 24 24'><path d='M6 3h12v18H6zM9 7h6M9 11h6M9 15h4'/></svg>",
  deduction:"<svg viewBox='0 0 24 24'><path d='M4 4h16v16H4zM8 12h8'/></svg>",
  warning:"<svg viewBox='0 0 24 24'><path d='M12 3 2 21h20L12 3zM12 9v5M12 18h.01'/></svg>",
  notice:"<svg viewBox='0 0 24 24'><path d='M12 3v12M12 20h.01'/></svg>",
  leaves:"<svg viewBox='0 0 24 24'><path d='M4 5h16v15H4zM8 3v4M16 3v4M4 10h16M8 14h3M8 18h6'/></svg>",
  notifications:"<svg viewBox='0 0 24 24'><path d='M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4'/></svg>",
  reminders:"<svg viewBox='0 0 24 24'><circle cx='12' cy='13' r='8'/><path d='M12 9v4l3 2M9 2h6'/></svg>",
  entities:"<svg viewBox='0 0 24 24'><path d='M3 21h18M5 21V5h10v16M15 10h4v11M8 9h4M8 13h4M8 17h4'/></svg>",
  settings:"<svg viewBox='0 0 24 24'><circle cx='12' cy='12' r='3'/><path d='M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-4v-.09A1.7 1.7 0 0 0 9 19.36a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.63 15 1.7 1.7 0 0 0 3.07 14H3v-4h.09A1.7 1.7 0 0 0 4.64 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.63h.01A1.7 1.7 0 0 0 10 3.07V3h4v.09A1.7 1.7 0 0 0 15 4.64a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.37 9v.01A1.7 1.7 0 0 0 20.93 10H21v4h-.09A1.7 1.7 0 0 0 19.4 15z'/></svg>"
};

const nav = [
  ["employees","الموظفين","employees"], ["schedules","جدول الدوامات","schedules"], ["attendance","تقرير البصمة","attendance"],
  ["separator"], ["decisions","قرارات وتعميمات إدارية","decisions"], ["deduction","كتاب خصم","deduction"], ["warning","كتاب تنبيه","warning"], ["notice","كتاب لفت نظر","notice"],
  ["separator"], ["leaves","الإجازات","leaves"], ["notifications","إشعارات","notifications"], ["reminders","تذكيرات","reminders"],
  ["separator"], ["entities","جهات العمل","entities"], ["settings","إعدادات","settings"]
];

const countries = [
  ["الكويت","+965","🇰🇼"],["السعودية","+966","🇸🇦"],["البحرين","+973","🇧🇭"],["قطر","+974","🇶🇦"],["الإمارات العربية المتحدة","+971","🇦🇪"],["عُمان","+968","🇴🇲"],["العراق","+964","🇮🇶"],["الأردن","+962","🇯🇴"],["فلسطين","+970","🇵🇸"],["لبنان","+961","🇱🇧"],["سوريا","+963","🇸🇾"],["مصر","+20","🇪🇬"],["اليمن","+967","🇾🇪"],["السودان","+249","🇸🇩"],["ليبيا","+218","🇱🇾"],["تونس","+216","🇹🇳"],["الجزائر","+213","🇩🇿"],["المغرب","+212","🇲🇦"],["موريتانيا","+222","🇲🇷"],["الصومال","+252","🇸🇴"],["جيبوتي","+253","🇩🇯"],["جزر القمر","+269","🇰🇲"],
  ["الهند","+91","🇮🇳"],["باكستان","+92","🇵🇰"],["بنغلاديش","+880","🇧🇩"],["سريلانكا","+94","🇱🇰"],["نيبال","+977","🇳🇵"],["الفلبين","+63","🇵🇭"],["إندونيسيا","+62","🇮🇩"],["ماليزيا","+60","🇲🇾"],["تركيا","+90","🇹🇷"],["إيران","+98","🇮🇷"],["أفغانستان","+93","🇦🇫"],["الصين","+86","🇨🇳"],["اليابان","+81","🇯🇵"],["كوريا الجنوبية","+82","🇰🇷"],["تايلاند","+66","🇹🇭"],["فيتنام","+84","🇻🇳"],["سنغافورة","+65","🇸🇬"],
  ["الولايات المتحدة","+1","🇺🇸"],["كندا","+1","🇨🇦"],["المملكة المتحدة","+44","🇬🇧"],["فرنسا","+33","🇫🇷"],["ألمانيا","+49","🇩🇪"],["إيطاليا","+39","🇮🇹"],["إسبانيا","+34","🇪🇸"],["هولندا","+31","🇳🇱"],["بلجيكا","+32","🇧🇪"],["سويسرا","+41","🇨🇭"],["السويد","+46","🇸🇪"],["النرويج","+47","🇳🇴"],["الدنمارك","+45","🇩🇰"],["فنلندا","+358","🇫🇮"],["روسيا","+7","🇷🇺"],["أوكرانيا","+380","🇺🇦"],["اليونان","+30","🇬🇷"],["رومانيا","+40","🇷🇴"],["أستراليا","+61","🇦🇺"],["نيوزيلندا","+64","🇳🇿"],
  ["إثيوبيا","+251","🇪🇹"],["إريتريا","+291","🇪🇷"],["كينيا","+254","🇰🇪"],["أوغندا","+256","🇺🇬"],["تنزانيا","+255","🇹🇿"],["نيجيريا","+234","🇳🇬"],["غانا","+233","🇬🇭"],["جنوب أفريقيا","+27","🇿🇦"],["البرازيل","+55","🇧🇷"],["الأرجنتين","+54","🇦🇷"],["المكسيك","+52","🇲🇽"]
];
const supportedCountryNames = ["الكويت","الهند","مصر","الفلبين","بنغلاديش","سوريا","الأردن","فلسطين","لبنان","اليمن"];
const supportedCountries = supportedCountryNames.map(name=>countries.find(country=>country[0]===name));
const LEGACY_FINGERPRINT_PLACES={
  "barcode-abu-al-hasaniya":{id:"barcode-abu-al-hasaniya",mode:"barcode",title:"باركود أبو الحصانية",branchKey:"abulhasania",branchName:"أبو الحصانية",barcodeToken:"bq-1782039493830-opsvylqd",barcodeValue:"HRMS-BASMA:bq-1782039493830-opsvylqd",location:{lat:29.342263,lng:48.018131},radiusMeters:30,restoredFromPrintedBarcode:true,createdAt:"2026-06-21T10:58:13.830Z",updatedAt:"2026-06-29T11:02:22.719Z"},
  "barcode-yarmouk":{id:"barcode-yarmouk",mode:"barcode",title:"باركود اليرموك",branchKey:"yarmouk",branchName:"اليرموك",barcodeToken:"bq-1782039427444-t1gcyrka",barcodeValue:"HRMS-BASMA:bq-1782039427444-t1gcyrka",location:{lat:29.342263,lng:48.018131},radiusMeters:30,restoredFromPrintedBarcode:true,createdAt:"2026-06-21T10:57:07.444Z",updatedAt:"2026-06-29T11:02:22.719Z"},
  "barcode-hawally":{id:"barcode-hawally",mode:"barcode",title:"باركود حولي",branchKey:"surra",branchName:"حولي",barcodeToken:"bq-1780311331449-wtnbcl1f",barcodeValue:"HRMS-BASMA:bq-1780311331449-wtnbcl1f",location:{lat:29.342263,lng:48.018131},radiusMeters:30,restoredFromPrintedBarcode:true,createdAt:"2026-06-01T10:55:31.449Z",updatedAt:"2026-06-29T11:02:22.719Z"}
};

const samples = [
  {id:"s1",fullName:"نورة خالد العتيبي",jobTitle:"رئيسة الموارد البشرية",workEntity:"الإدارة العامة",dailyHours:8,scheduleType:"fixed"},
  {id:"s2",fullName:"أحمد يوسف الشمري",jobTitle:"أخصائي شؤون موظفين",workEntity:"فرع العاصمة",dailyHours:8,scheduleType:"variable"},
  {id:"s3",fullName:"مريم عبدالعزيز القطان",jobTitle:"محاسبة رواتب",workEntity:"الإدارة العامة",dailyHours:7,scheduleType:"fixed"}
];

const digits = (value="") => String(value).replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d)).replace(/[۰-۹]/g,d=>"۰۱۲۳۴۵۶۷۸۹".indexOf(d));
const onlyDigits = (value="") => digits(value).replace(/\D/g,"");
const initials = (name="") => name.split(" ").slice(0,2).map(x=>x[0]||"").join("");
const escapeHtml = (value="") => String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const sleep = ms => new Promise(resolve=>setTimeout(resolve,ms));
const AUTH_SESSION_MARKER="rakaez-auth-session-v2";
const IDLE_SESSION_TIMEOUT=15*60*1000;
let sessionTimer=null,lastSessionActivity=0,sessionActivityBound=false;
const countryByName = name => countries.find(x=>x[0]===name) || countries[0];
const countryByDial = dial => supportedCountries.find(x=>x[1]===dial) || supportedCountries[0];
const employeePhotoSrc = employee => employee?.photoDataUrl || employee?.photoUrl || "";
const dialOptions = selected => supportedCountries.map(country=>`<option value="${country[1]}" ${country[1]===selected?"selected":""}>${country[2]} ${country[1]} · ${country[0]}</option>`).join("");
const phoneField = (numberName,dialName,selected="+965",required=false) => `<div class="phone editable-phone"><select name="${dialName}" class="dial-select" aria-label="فتح الخط">${dialOptions(selected)}</select><input name="${numberName}" class="english-number" inputmode="numeric" maxlength="15" placeholder="رقم الهاتف" ${required?"required":""}></div>`;
const durationHours = (from,to) => { const [fh,fm]=from.split(":").map(Number), [th,tm]=to.split(":").map(Number); let minutes=(th*60+tm)-(fh*60+fm); if(minutes<=0) minutes+=1440; return minutes/60; };
const formatHours = n => Number.isInteger(n)?String(n):String(Math.round(n*100)/100);
const timeParts = value => { const [hour24,minute]=value.split(":").map(Number); return {hour:hour24%12||12,minute:minute>=30?"30":"00",period:hour24>=12?"pm":"am"}; };
const timeValue = prefix => { const hour=Number($(`#${prefix}-hour`).value),minute=$(`#${prefix}-minute`).value,period=$(`#${prefix}-period`).value; const hour24=period==="pm"?(hour%12)+12:hour%12; return `${String(hour24).padStart(2,"0")}:${minute}`; };
const formatArabicTime = value => { const parts=timeParts(value); return `${String(parts.hour).padStart(2,"0")}:${parts.minute} ${parts.period==="am"?"صباحاً":"مساءً"}`; };
function timePicker(prefix,value){const parts=timeParts(value);return `<div class="custom-time-picker" dir="ltr"><select id="${prefix}-hour" aria-label="الساعة">${Array.from({length:12},(_,i)=>i+1).map(hour=>`<option value="${hour}" ${hour===parts.hour?"selected":""}>${String(hour).padStart(2,"0")}</option>`).join("")}</select><b>:</b><select id="${prefix}-minute" aria-label="الدقائق"><option value="00" ${parts.minute==="00"?"selected":""}>00</option><option value="30" ${parts.minute==="30"?"selected":""}>30</option></select><select id="${prefix}-period" class="period-select" aria-label="الفترة"><option value="am" ${parts.period==="am"?"selected":""}>صباحاً</option><option value="pm" ${parts.period==="pm"?"selected":""}>مساءً</option></select></div>`;}

function showToast(message){const el=$("#toast");el.innerHTML=`<i>✓</i><div><b>تمت العملية بنجاح</b><p>${escapeHtml(message)}</p></div>`;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),4500);}
function showError(message){const el=$("#form-message");if(el){el.textContent=message;el.className="form-message error";el.scrollIntoView({behavior:"smooth",block:"center"});}}
function passwordField(id,placeholder=""){return `<div class="password-field"><input id="${id}" type="password" placeholder="${placeholder}" minlength="6" required><button type="button" class="password-toggle" aria-label="إظهار كلمة المرور" aria-pressed="false"><svg viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12z"/><circle cx="12" cy="12" r="3"/></svg></button></div>`;}
function bindPasswordToggles(){document.querySelectorAll(".password-toggle").forEach(button=>button.onclick=()=>{const input=button.previousElementSibling;const visible=input.type==="text";input.type=visible?"password":"text";button.classList.toggle("visible",!visible);button.setAttribute("aria-pressed",String(!visible));button.setAttribute("aria-label",visible?"إظهار كلمة المرور":"إخفاء كلمة المرور");});}

function stopSessionSecurity(){clearTimeout(sessionTimer);sessionTimer=null;}
async function expireSecureSession(){if(!state.user||state.demo)return;stopSessionSecurity();sessionStorage.removeItem(AUTH_SESSION_MARKER);state.sessionExpired=true;await signOut(auth);}
function resetSessionSecurity(){if(!state.user||state.demo)return;lastSessionActivity=Date.now();clearTimeout(sessionTimer);sessionTimer=setTimeout(expireSecureSession,IDLE_SESSION_TIMEOUT);}
function startSessionSecurity(){if(!state.user||state.demo)return;resetSessionSecurity();if(sessionActivityBound)return;sessionActivityBound=true;["pointerdown","keydown","touchstart","scroll"].forEach(eventName=>window.addEventListener(eventName,resetSessionSecurity,{passive:true}));document.addEventListener("visibilitychange",()=>{if(document.hidden||!state.user)return;if(Date.now()-lastSessionActivity>=IDLE_SESSION_TIMEOUT)expireSecureSession();else resetSessionSecurity();});}

async function initialize(){await setPersistence(auth,browserSessionPersistence);onAuthStateChanged(auth,async user=>{if(user&&!state.demo&&sessionStorage.getItem(AUTH_SESSION_MARKER)!=="active"){await signOut(auth);return;}state.user=user;$("#loading").classList.add("hidden");if(user||state.demo){startSessionSecurity();openDashboard();}else{stopSessionSecurity();openAuth();}});}
function openAuth(mode="login"){$("#dashboard").classList.add("hidden");$("#auth-page").classList.remove("hidden");renderAuth(mode);}
function renderAuth(mode="login"){
  const card=$("#auth-card");
  if(mode==="otp"&&state.pendingLogin){card.innerHTML=`<div class="auth-heading"><span>◈</span><h2>تحقق من واتساب</h2></div><form id="otp-form"><label>رمز الدخول<input id="login-code" class="otp-input" inputmode="numeric" maxlength="6" placeholder="— — — — — —" autofocus required></label><p id="form-message" class="form-message hidden"></p><button class="primary wide">تحقق وادخل للنظام</button></form><button id="back-login" class="text-btn wide">العودة إلى تسجيل الدخول</button>`;$("#otp-form").onsubmit=verifyLoginOtp;$("#back-login").onclick=()=>{state.pendingLogin=null;renderAuth("login");};return;}
  if(mode==="register"){card.innerHTML=`<div class="auth-heading"><span>♙</span><h2>إنشاء حساب المنشأة</h2></div><form id="register-form"><label>البريد الإلكتروني<input id="reg-email" type="email" required></label><label>رقم الهاتف الكويتي<div class="phone"><span>🇰🇼 +965</span><input id="reg-phone" inputmode="numeric" maxlength="8" required></div></label><label>كلمة المرور${passwordField("reg-password")}</label><button class="primary wide">إرسال رموز التحقق</button><p id="form-message" class="form-message hidden"></p></form><button id="back-login" class="text-btn wide">لدي حساب بالفعل</button>`;$("#register-form").onsubmit=requestSignup;$("#back-login").onclick=()=>renderAuth("login");bindPasswordToggles();bindEnglishNumbers(card);return;}
  card.innerHTML=`<div class="auth-heading"><span>✓</span><h2>مرحباً بعودتك</h2></div>${state.sessionExpired?'<p class="form-message">انتهت الجلسة لعدم الاستخدام. سجّل الدخول مجدداً للمتابعة.</p>':""}<form id="login-form"><label>البريد الإلكتروني أو رقم الهاتف<input id="identifier" placeholder="name@company.com أو 5XXXXXXX" required></label><label>رمز المرور${passwordField("password","اكتب رمز المرور")}</label><p id="form-message" class="form-message hidden"></p><button class="primary wide">دخول آمن ←</button></form><div class="divider"><span>حساب جديد</span></div><button id="register-btn" class="secondary wide">＋ إنشاء حساب</button><button id="demo-btn" class="text-btn wide">معاينة النظام بدون تسجيل</button>`;
  $("#login-form").onsubmit=beginLogin;$("#register-btn").onclick=()=>renderAuth("register");$("#demo-btn").onclick=()=>{state.demo=true;state.employees=[...samples];openDashboard();};bindPasswordToggles();
}

async function resolveEmail(identifier){if(identifier.includes("@"))return identifier.trim();const phone=onlyDigits(identifier).slice(-8);const snap=await get(ref(db,`phoneDirectory/${phone}`));if(!snap.exists())throw new Error("لم يتم العثور على حساب بهذا الرقم");return snap.val().email;}
async function beginLogin(event){event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent="جارٍ التحقق...";try{const identifier=$("#identifier").value,password=$("#password").value,email=await resolveEmail(identifier);const check=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${CONFIG.firebase.apiKey}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password,returnSecureToken:true})});const identity=await check.json();if(!check.ok)throw new Error("البريد أو رقم الهاتف أو كلمة المرور غير صحيحة");const profile=await fetch(`${CONFIG.firebase.databaseURL}/userProfiles/${identity.localId}.json?auth=${identity.idToken}`).then(r=>r.json());const phone=String(profile?.phone||onlyDigits(identifier));if(phone.length<8)throw new Error("لا يوجد رقم واتساب مسجل لهذا الحساب");const request=await fetch(CONFIG.n8n.loginOtpUrl,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone,email,purpose:"hrms_login"})});const data=await request.json();if(!request.ok||data.ok===false)throw new Error(data.message||"تعذر إرسال رمز الدخول");state.pendingLogin={email,password,phone};renderAuth("otp");}catch(error){showError(error.message||"تعذر تسجيل الدخول");button.disabled=false;button.textContent="دخول آمن ←";}}
async function verifyLoginOtp(event){event.preventDefault();const code=onlyDigits($("#login-code").value),button=event.submitter;button.disabled=true;try{const verify=await fetch(CONFIG.n8n.verifyOtpUrl,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone:state.pendingLogin.phone,code,purpose:"hrms_login"})});const data=await verify.json();if(!verify.ok||!data.ok)throw new Error(data.message||"رمز الدخول غير صحيح");sessionStorage.setItem(AUTH_SESSION_MARKER,"active");state.sessionExpired=false;await signInWithEmailAndPassword(auth,state.pendingLogin.email,state.pendingLogin.password);state.pendingLogin=null;}catch(error){sessionStorage.removeItem(AUTH_SESSION_MARKER);showError(error.message);button.disabled=false;}}
async function requestSignup(event){event.preventDefault();if(!CONFIG.n8n.emailOtpUrl||!CONFIG.n8n.whatsappSignupOtpUrl)return showError("لم يتم إعداد بريد الإرسال وإنشاء الحساب بعد. تسجيل الدخول عبر واتساب جاهز.");}

function openDashboard(){$("#auth-page").classList.add("hidden");$("#dashboard").classList.remove("hidden");const identity=state.user?.email||"وضع المعاينة";$("#user-email").textContent=identity;$("#user-avatar").textContent=identity[0]?.toUpperCase()||"م";$("#header-avatar").textContent=identity[0]?.toUpperCase()||"م";renderNav();bindData();renderPage();}
function renderNav(){$("#side-nav").innerHTML=nav.map(item=>item[0]==="separator"?'<div class="nav-separator" aria-hidden="true"></div>':`<button data-page="${item[0]}" class="${state.page===item[0]?"active":""}"><i>${icons[item[2]]}</i><span>${item[1]}</span>${item[0]==="notifications"?"<em>3</em>":""}</button>`).join("");$("#side-nav").querySelectorAll("button").forEach(button=>button.onclick=()=>{state.page=button.dataset.page;renderNav();renderPage();});}
function bindData(){if(state.demo||!state.user||state.bound)return;state.bound=true;onValue(ref(db,"organizations/default/employees"),snap=>{const value=snap.val()||{};state.employees=Object.entries(value).map(([id,v])=>({id,...v}));renderPage();});onValue(ref(db,"organizations/default/workEntities"),snap=>{if(snap.exists())state.entities=Object.values(snap.val());renderPage();});onValue(ref(db,"organizations/default/settings"),snap=>{state.settings={companyLogoUrl:"",companyLogoDataUrl:"",...(snap.val()||{})};renderPage();});onValue(ref(db,"organizations/default/leaves"),snap=>{const value=snap.val()||{};state.leaves=Object.entries(value).map(([id,v])=>({id,...v}));renderPage();});onValue(ref(db,"organizations/default/fingerprintPlaces"),snap=>{state.fingerprintPlaces=Object.entries(snap.val()||{}).map(([id,value])=>({id,...value}));if(state.page==="fingerprint-places"||state.page==="settings")renderPage();});onValue(ref(db,"organizations/default/attendance"),snap=>{state.attendance=snap.val()||{};if(state.page==="attendance")refreshAttendanceReport();});onValue(ref(db,"organizations/default/schedules"),snap=>{state.schedules=snap.val()||{};if(state.page==="attendance")refreshAttendanceReport();});}
function hero(title,_subtitle,button=""){return `<section class="page-hero"><div><span class="eyebrow">قاعدة بيانات الموارد البشرية</span><h1>${title}</h1></div>${button}</section>`;}
function renderPage(){const item=nav.find(x=>x[0]===state.page);const label=item?.[1]||(state.page==="add"?"إدراج موظف":state.page==="profile"?"بيانات الموظف":state.page==="fingerprint-places"?"أماكن البصمة":"الموظفين");$("#page-title").textContent=label;if(state.page==="employees")renderEmployees();else if(state.page==="add")renderEmployeeForm();else if(state.page==="profile")renderEmployeeProfile();else if(state.page==="entities")renderEntities();else if(state.page==="leaves")renderLeaves();else if(state.page==="schedules")renderSchedules();else if(state.page==="attendance")renderAttendanceReport();else if(state.page==="fingerprint-places")renderFingerprintPlaces();else if(state.page==="settings")renderSettings();else renderGeneric(label);window.scrollTo({top:0,behavior:"smooth"});}

function renderEmployees(){
  const list=state.employees.filter(e=>[e.fullName,e.jobTitle,e.workEntity].some(v=>String(v||"").includes(state.search)));
  $("#page-content").innerHTML=`${hero("الموظفون","",'<div class="employee-page-actions"><button id="add-employee" class="primary">＋ إدراج موظف</button></div>')}<div class="toolbar"><label class="search-box">⌕<input id="employee-search" placeholder="ابحث بالاسم أو المسمى أو جهة العمل" value="${escapeHtml(state.search)}"></label><div class="chips"><button class="active">الكل <span>${state.employees.length}</span></button><button>دوام ثابت</button><button>حسب الجدول</button></div></div><div class="employees-grid">${list.length?list.map(employeeCard).join(""):'<div class="empty"><b>لا توجد نتائج</b></div>'}</div>`;
  $("#add-employee").onclick=()=>{state.page="add";state.draftSegments=[];renderNav();renderPage();};
  $("#employee-search").oninput=e=>{state.search=e.target.value;renderEmployees();};
  document.querySelectorAll(".employee-card").forEach(card=>{card.ondblclick=()=>{state.profileEmployeeId=card.dataset.employeeId;state.page="profile";renderPage();};});
  document.querySelectorAll(".employee-card .bell").forEach(button=>button.onclick=event=>event.stopPropagation());
}
function employeeCard(e){const photo=employeePhotoSrc(e);return `<article class="employee-card" data-employee-id="${escapeHtml(e.id)}" tabindex="0"><div class="card-cover"><span class="status ${e.scheduleType||"fixed"}"></span><div class="avatar">${photo?`<img src="${escapeHtml(photo)}" alt="صورة ${escapeHtml(e.fullName)}">`:initials(e.fullName)}</div><button class="bell" aria-label="إشعارات الموظف">${icons.notifications}<span><b>آخر الإشعارات</b><small>طلب تعديل بصمة</small><small>إجازة بانتظار الاعتماد</small></span></button></div><div class="employee-info"><h3>${escapeHtml(e.fullName)}</h3><p>${escapeHtml(e.jobTitle||"")}</p><div class="entity">▥ ${escapeHtml(e.workEntity||"")}</div><footer><span>◷ ${e.dailyHours||0} ساعات</span><em class="${e.scheduleType||"fixed"}">${e.scheduleType==="variable"?"حسب الجدول":"دوام ثابت"}</em></footer></div></article>`;}

function profileDataRow(label,value){return `<div><small>${escapeHtml(label)}</small><b>${escapeHtml(value||"—")}</b></div>`;}
function employeePhoneText(phone){return phone?.phone?`${phone.dialCode||""} ${phone.phone}`.trim():"—";}
function renderEmployeeProfile(){
  const employee=state.employees.find(item=>item.id===state.profileEmployeeId);
  if(!employee){state.page="employees";renderPage();return;}
  const photo=employeePhotoSrc(employee),alternates=employee.alternatePhones||[],relatives=employee.relatives||[],segments=employee.segments||[];
  $("#page-content").innerHTML=`<div class="form-page-heading profile-page-heading"><button id="back-employees" class="back-btn">→</button><div><span>الموظفون / ملف الموظف</span><h1>بيانات ${escapeHtml(employee.fullName)}</h1></div><button id="edit-employee" class="primary">✎ تعديل البيانات وإضافة صورة</button></div><section class="employee-profile"><header class="employee-profile-header"><div class="profile-photo-large">${photo?`<img src="${escapeHtml(photo)}" alt="صورة ${escapeHtml(employee.fullName)}">`:`<span>${initials(employee.fullName)}</span>`}</div><div><span class="eyebrow">ملف الموظف</span><h2>${escapeHtml(employee.fullName)}</h2><p>${escapeHtml(employee.jobTitle||"المسمى الوظيفي غير محدد")}</p><em class="${employee.scheduleType||"fixed"}">${employee.scheduleType==="variable"?"ساعات متغيرة حسب الجدول":"ساعات عمل ثابتة"}</em></div><dl><div><dt>ساعات العمل</dt><dd>${formatHours(Number(employee.dailyHours)||0)} ساعة / يوم</dd></div><div><dt>رمز البصمة</dt><dd>${employee.attendancePin?"••••"+String(employee.attendancePin).slice(-2):"غير محدد"}</dd></div></dl></header><div class="profile-sections"><section><h3>البيانات الأساسية</h3><div class="profile-data-grid">${profileDataRow("الاسم الكامل",employee.fullName)}${profileDataRow("الرقم المدني",employee.civilId)}${profileDataRow("الجنسية",employee.nationality)}${profileDataRow("المسمى الوظيفي",employee.jobTitle)}${profileDataRow("جهة العمل",employee.workEntity)}</div></section><section><h3>معلومات التواصل</h3><div class="profile-data-grid">${profileDataRow("رقم الهاتف الشخصي",employeePhoneText(employee.primaryPhone))}${alternates.map((phone,index)=>profileDataRow(`رقم الهاتف الاحتياطي ${index+1}`,employeePhoneText(phone))).join("")||profileDataRow("الأرقام الاحتياطية","لا توجد أرقام مضافة")}</div>${relatives.length?`<div class="profile-relatives">${relatives.map((relative,index)=>`<div><b>القريب ${index+1}</b><span>${escapeHtml(relative.relation||"صلة القرابة غير محددة")}</span><small>${escapeHtml(employeePhoneText(relative))}</small></div>`).join("")}</div>`:""}</section><section><h3>ساعات العمل</h3><div class="profile-data-grid">${profileDataRow("عدد ساعات العمل",`${formatHours(Number(employee.dailyHours)||0)} ساعات / يوم`)}${profileDataRow("طريقة الدوام",employee.scheduleType==="variable"?"حسب جدول الدوامات":"ساعات عمل ثابتة")}${profileDataRow("فترات العمل الثابتة",segments.length?`${segments.length} فترات`:"لم يتم توزيع المهام")}</div></section></div></section>`;
  $("#back-employees").onclick=()=>{state.page="employees";state.profileEmployeeId=null;renderPage();};
  $("#edit-employee").onclick=()=>openEmployeeEditor(employee.id);
}

async function readEmployeePhoto(file){
  if(!file)return "";
  if(!file.type.startsWith("image/"))throw new Error("يرجى اختيار صورة بصيغة PNG أو JPG أو WEBP.");
  if(file.size>6*1024*1024)throw new Error("حجم الصورة كبير جداً. اختر صورة أقل من 6 ميغابايت.");
  const objectUrl=URL.createObjectURL(file);
  try{
    const image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("تعذر قراءة الصورة."));img.src=objectUrl;});
    let width=Math.min(image.naturalWidth||640,700),height=Math.round((image.naturalHeight||640)*width/(image.naturalWidth||640)),quality=.86,dataUrl="";
    for(let attempt=0;attempt<5;attempt++){
      const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;
      canvas.getContext("2d").drawImage(image,0,0,width,height);
      dataUrl=canvas.toDataURL("image/jpeg",quality);
      if(dataUrl.length<800000)break;
      width=Math.round(width*.78);height=Math.round(height*.78);quality=Math.max(.62,quality-.07);
    }
    if(dataUrl.length>=800000)throw new Error("تعذر ضغط الصورة للحجم المناسب. اختر صورة أصغر.");
    return dataUrl;
  }finally{URL.revokeObjectURL(objectUrl);}
}

function editorCountryOptions(selected=""){return supportedCountries.map(country=>`<option value="${country[0]}" ${country[0]===selected?"selected":""}>${country[2]} ${country[0]}</option>`).join("");}
function openEmployeeEditor(employeeId){
  const employee=state.employees.find(item=>item.id===employeeId);if(!employee)return;
  const photo=employeePhotoSrc(employee),root=$("#modal-root"),primary=employee.primaryPhone||{},altPhones=employee.alternatePhones||[];
  root.innerHTML=`<div class="modal-backdrop employee-editor-backdrop"><section class="modal employee-editor-modal" role="dialog" aria-modal="true" aria-labelledby="employee-editor-title"><header><div><span>ملف الموظف</span><h3 id="employee-editor-title">تعديل بيانات ${escapeHtml(employee.fullName)}</h3></div><button type="button" class="modal-close" aria-label="إغلاق">×</button></header><form id="employee-editor-form"><div class="editor-photo-row"><label class="editor-photo-picker"><input id="editor-photo" type="file" accept="image/png,image/jpeg,image/webp"><span id="editor-photo-preview">${photo?`<img src="${escapeHtml(photo)}" alt="">`:initials(employee.fullName)}</span><b>تغيير الصورة الشخصية</b></label></div><div class="editor-grid"><label>الاسم الكامل<input name="fullName" value="${escapeHtml(employee.fullName)}" required></label><label>الرقم المدني<input name="civilId" class="english-number" inputmode="numeric" maxlength="12" value="${escapeHtml(employee.civilId||"")}" required></label><label>الجنسية<select name="nationality"><option value="">اختر الجنسية</option>${editorCountryOptions(employee.nationality||"")}</select></label><label>المسمى الوظيفي<input name="jobTitle" value="${escapeHtml(employee.jobTitle||"")}" required></label><label class="wide-field">جهة العمل<select name="workEntity" required><option value="">اختر جهة العمل</option>${state.entities.map(entity=>`<option ${entity===employee.workEntity?"selected":""}>${escapeHtml(entity)}</option>`).join("")}</select></label><label>رقم الهاتف الشخصي${phoneField("primaryPhone","primaryDial",primary.dialCode||"+965")}</label><label>عدد ساعات العمل<input name="dailyHours" class="english-number" inputmode="decimal" value="${escapeHtml(employee.dailyHours||8)}" required></label><label>رمز دخول البصمة<input name="attendancePin" class="english-number" inputmode="numeric" minlength="4" maxlength="8" value="${escapeHtml(employee.attendancePin||"")}" required></label><label>طريقة الدوام<select name="scheduleType"><option value="variable" ${employee.scheduleType==="variable"?"selected":""}>حسب جدول الدوامات</option><option value="fixed" ${employee.scheduleType!=="variable"?"selected":""}>ساعات عمل ثابتة</option></select></label></div><p id="employee-editor-error" class="form-message error hidden"></p><footer><button type="button" class="secondary modal-cancel">إلغاء</button><button class="primary">حفظ التعديلات</button></footer></form></section></div>`;
  root.querySelector('[name="primaryPhone"]').value=primary.phone||"";
  const close=()=>root.innerHTML="";
  $(".modal-close").onclick=$(".modal-cancel").onclick=close;
  $(".employee-editor-backdrop").onclick=event=>{if(event.target.classList.contains("employee-editor-backdrop"))close();};
  bindEnglishNumbers(root);
  let nextPhotoDataUrl=employee.photoDataUrl||"";
  $("#editor-photo").onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{nextPhotoDataUrl=await readEmployeePhoto(file);$("#editor-photo-preview").innerHTML=`<img src="${escapeHtml(nextPhotoDataUrl)}" alt="معاينة الصورة">`;}catch(error){const message=$("#employee-editor-error");message.textContent=error.message;message.classList.remove("hidden");}};
  $("#employee-editor-form").onsubmit=async event=>{
    event.preventDefault();const form=event.target,data=Object.fromEntries(new FormData(form)),error=$("#employee-editor-error"),attendancePin=onlyDigits(data.attendancePin),primaryPhone=onlyDigits(data.primaryPhone),dailyHours=Number(data.dailyHours);
    if(attendancePin.length<4||attendancePin.length>8){error.textContent="رمز دخول البصمة يجب أن يتكون من 4 إلى 8 أرقام.";error.classList.remove("hidden");return;}
    if(!dailyHours||dailyHours>24){error.textContent="أدخل عدد ساعات عمل صحيحاً من 1 إلى 24.";error.classList.remove("hidden");return;}
    if(state.employees.some(item=>item.id!==employee.id&&String(item.attendancePin||"")===attendancePin)){error.textContent="رمز دخول البصمة مستخدم لموظف آخر.";error.classList.remove("hidden");return;}
    const previousPin=String(employee.attendancePin||""),record={...employee,fullName:data.fullName.trim(),civilId:onlyDigits(data.civilId),nationality:data.nationality||"",jobTitle:data.jobTitle.trim(),workEntity:data.workEntity,dailyHours,scheduleType:data.scheduleType,attendancePin,primaryPhone:primaryPhone?{phone:primaryPhone,dialCode:data.primaryDial,country:countryByDial(data.primaryDial)[0]}:null,photoDataUrl:nextPhotoDataUrl,photoUrl:nextPhotoDataUrl?"":employee.photoUrl||"",updatedAt:Date.now()};
    try{
      if(state.demo){state.employees=state.employees.map(item=>item.id===employee.id?record:item);}else if(state.user){
        if(previousPin!==attendancePin){const pinRef=ref(db,`organizations/default/attendancePins/${attendancePin}`),reservation=await runTransaction(pinRef,current=>current===null||current===employee.id?employee.id:undefined,{applyLocally:false});if(!reservation.committed)throw new Error("رمز دخول البصمة مستخدم لموظف آخر.");if(previousPin)await remove(ref(db,`organizations/default/attendancePins/${previousPin}`)).catch(()=>{});}
        await set(ref(db,`organizations/default/employees/${employee.id}`),record);
      }
      state.profileEmployeeId=employee.id;close();showToast(`تم تعديل بيانات ${record.fullName}`);renderEmployeeProfile();
    }catch(saveError){error.textContent=saveError.message||"تعذر حفظ التعديلات.";error.classList.remove("hidden");}
  };
}

function renderEmployeeForm(){
  state.draftSegments=[];
  $("#page-content").innerHTML=`<div class="form-page-heading"><button id="back-employees" class="back-btn">→</button><div><span>الموظفون / إدراج موظف</span><h1>إدراج موظف جديد</h1></div></div><form id="employee-form" class="employee-form" novalidate>
  <section><div class="section-head"><span>01</span><div><h3>بيانات الموظف الأساسية</h3></div></div><label class="photo-upload"><input id="photo" type="file" accept="image/png,image/jpeg,image/webp"><span class="photo-preview">＋</span><b>إدراج صورة عرض</b></label><div class="form-grid"><label>اسم الموظف *<input name="fullName" autocomplete="name" required></label><label>الرقم المدني *<input name="civilId" class="english-number" inputmode="numeric" maxlength="12" required></label><label>الجنسية<div class="search-select"><input id="nationality" name="nationality" list="countries-list" autocomplete="off" placeholder="اختر الجنسية"><span>⌄</span><datalist id="countries-list">${supportedCountries.map(c=>`<option value="${c[0]}">${c[2]} ${c[0]}</option>`).join("")}</datalist></div></label><label>المسمى الوظيفي *<input name="jobTitle" required></label><label class="wide-field">جهة العمل *<select name="workEntity" required><option value="">اختر جهة العمل</option>${state.entities.map(e=>`<option>${escapeHtml(e)}</option>`).join("")}</select></label><label class="wide-field attendance-pin-field">رمز دخول البصمة *${attendancePinField()}</label></div></section>
  <section><div class="section-head"><span>02</span><div><h3>معلومات التواصل الشخصية</h3></div></div><div class="employee-phones-group"><div class="primary-phone-row"><div class="primary-phone-block"><label>رقم الهاتف الشخصي${phoneField("primaryPhone","primaryDial")}</label></div><button type="button" id="add-alternate-phone" class="circle-add" aria-label="إضافة رقم هاتف احتياطي" title="إضافة رقم هاتف احتياطي">＋</button></div><div id="alternate-phones" class="alternate-phones"></div></div><div class="relatives-head"><div><h4>أرقام هواتف أقرب الأشخاص</h4></div><button type="button" id="add-relative" class="circle-add" aria-label="إضافة قريب">＋</button></div><div id="relatives-list" class="relatives-list"></div></section>
  <section><div class="section-head"><span>03</span><div><h3>ساعات العمل وتوزيع المهام</h3></div></div><div class="hours-row"><label>عدد ساعات العمل للموظف *<div class="hours-input"><input id="daily-hours" name="dailyHours" class="english-number" inputmode="decimal" value="8" required><span>ساعة / يوم</span></div></label><fieldset class="schedule-choice"><legend>طريقة الدوام *</legend><label><input type="radio" name="scheduleType" value="variable" checked><span><i>▦</i><b>حسب جدول الدوامات</b></span></label><label><input type="radio" name="scheduleType" value="fixed"><span><i>✓</i><b>ساعات عمل ثابتة</b></span></label></fieldset></div><div id="fixed-schedule" class="fixed-schedule hidden"><div class="distribution-title"><div><h4>توزيع ساعات العمل</h4></div><strong id="distribution-count">0 من 8 ساعات</strong></div><div class="timeline-row"><button type="button" id="add-segment" class="timeline-add" aria-label="إضافة فترة">＋</button><div id="work-timeline" class="work-timeline"></div></div></div></section>
  <p id="form-message" class="form-message hidden"></p><div class="form-actions"><button type="button" id="cancel-employee" class="secondary">إلغاء</button><button class="primary submit">＋ إضافة الموظف</button></div></form>`;
  bindEmployeeForm();
}

function bindEnglishNumbers(root=document){root.querySelectorAll(".english-number").forEach(input=>input.addEventListener("input",()=>{const allowDecimal=input.classList.contains("decimal-number")||input.id==="daily-hours"||input.name==="dailyHours";let value=digits(input.value).replace(allowDecimal?/[^0-9.]/g:/\D/g,"");if(allowDecimal){const parts=value.split(".");value=parts.shift()+(parts.length?"."+parts.join(""):"");}input.value=value;}));}
function attendancePinField(){return `<div class="attendance-pin-slots" data-attendance-pin><input name="attendancePin" class="english-number pin-input" inputmode="numeric" minlength="4" maxlength="8" autocomplete="off" aria-label="رمز دخول البصمة" required><div class="pin-slot-display" aria-hidden="true"></div></div>`;}
function updateAttendancePinMask(box){const input=box.querySelector("input"),value=onlyDigits(input.value).slice(0,8),slotCount=Math.max(4,value.length);input.value=value;box.querySelector(".pin-slot-display").innerHTML=Array.from({length:slotCount},(_,index)=>`<span class="${index<value.length?"filled":""}">${value[index]||"—"}</span>`).join("");}
function bindAttendancePinMask(root=document){root.querySelectorAll("[data-attendance-pin]").forEach(box=>{const input=box.querySelector("input");updateAttendancePinMask(box);input.addEventListener("input",()=>updateAttendancePinMask(box));box.addEventListener("click",()=>input.focus());});}
function addAlternatePhoneRow(){const list=$("#alternate-phones"),index=list.children.length;const row=document.createElement("div");row.className="alternate-phone-row";row.innerHTML=`<label>رقم الهاتف الاحتياطي ${index+1}${phoneField("alternatePhone","alternateDial")}</label><button type="button" class="remove-relative" aria-label="حذف الرقم الاحتياطي">×</button>`;list.appendChild(row);row.querySelector(".remove-relative").onclick=()=>{row.remove();renumberAlternatePhones();};bindEnglishNumbers(row);}
function renumberAlternatePhones(){document.querySelectorAll(".alternate-phone-row").forEach((row,i)=>row.querySelector("label").childNodes[0].textContent=`رقم الهاتف الاحتياطي ${i+1}`);}
function addRelativeRow(){const list=$("#relatives-list"),index=list.children.length;const row=document.createElement("div");row.className="relative-row";row.innerHTML=`<label>الرقم ${index+1}${phoneField("relativePhone","relativeDial")}</label><label>نوع القرابة<input name="relation" placeholder="مثال: الأب، الزوجة، الأخ"></label>${index?'<button type="button" class="remove-relative" aria-label="حذف الرقم">×</button>':'<span></span>'}`;list.appendChild(row);row.querySelector(".remove-relative")?.addEventListener("click",()=>{row.remove();renumberRelatives();});bindEnglishNumbers(row);}
function renumberRelatives(){document.querySelectorAll(".relative-row").forEach((row,i)=>row.querySelector("label").childNodes[0].textContent=`الرقم ${i+1}`);}
function bindEmployeeForm(){
  $("#back-employees").onclick=$("#cancel-employee").onclick=()=>{state.page="employees";renderNav();renderPage();};
  $("#photo").onchange=e=>{const file=e.target.files[0];if(!file)return;const preview=$(".photo-preview");preview.innerHTML=`<img src="${URL.createObjectURL(file)}" alt="معاينة الصورة">`;preview.parentElement.classList.add("has-photo");};
  $("#add-alternate-phone").onclick=addAlternatePhoneRow;
  $("#add-relative").onclick=addRelativeRow;addRelativeRow();
  bindEnglishNumbers($("#employee-form"));
  bindAttendancePinMask($("#employee-form"));
  document.querySelectorAll('input[name="scheduleType"]').forEach(input=>input.onchange=()=>{$("#fixed-schedule").classList.toggle("hidden",input.value!=="fixed"||!input.checked);});
  $("#daily-hours").oninput=()=>{const input=$("#daily-hours");input.value=digits(input.value).replace(/[^0-9.]/g,"");const total=Number(input.value)||0;const used=state.draftSegments.reduce((sum,s)=>sum+s.hours,0);if(used>total)state.draftSegments=[];renderTimeline();};
  $("#add-segment").onclick=()=>openSegmentModal();renderTimeline();
  $("#employee-form").onsubmit=saveEmployee;
}

function renderTimeline(){const total=Number($("#daily-hours")?.value)||0,used=state.draftSegments.reduce((sum,s)=>sum+s.hours,0),remaining=Math.max(0,total-used),timeline=$("#work-timeline");if(!timeline)return;const colors=["#0f766e","#2563a8","#c58a2c","#7b5cab","#be5b70","#2f8f63"];timeline.innerHTML=state.draftSegments.map((s,i)=>`<button type="button" class="timeline-segment" data-index="${i}" style="flex:${s.hours};background:${colors[i%colors.length]}" title="تعديل الفترة"><b>${formatArabicTime(s.from)} — ${formatArabicTime(s.to)}</b><span>${s.tasks.map(escapeHtml).join(" <i>＋</i> ")}</span><em>${formatHours(s.hours)} س</em></button>`).join("")+(remaining?`<div class="timeline-remaining" style="flex:${remaining}"><b>${formatHours(remaining)} ساعات متبقية</b><span>لم يتم توزيعها بعد</span></div>`:"");if(!total)timeline.innerHTML='<div class="timeline-remaining" style="flex:1"><b>أدخل عدد ساعات العمل</b></div>';$("#distribution-count").textContent=`${formatHours(used)} من ${formatHours(total)} ساعات`;$("#timeline-help").textContent=remaining?`متبقي ${formatHours(remaining)} ساعات لإكمال التوزيع`:"اكتمل توزيع جميع ساعات العمل ✓";$("#timeline-help").classList.toggle("complete",Boolean(total&&!remaining));$("#add-segment").disabled=!total||remaining<=0;timeline.querySelectorAll(".timeline-segment").forEach(button=>button.onclick=()=>openSegmentModal(Number(button.dataset.index)));}
function openSegmentModal(editIndex=null){const editing=editIndex!==null,segment=editing?state.draftSegments[editIndex]:{from:"08:00",to:"14:00",tasks:[""]};$("#modal-root").innerHTML=`<div class="modal-backdrop"><section class="modal work-segment-modal" role="dialog" aria-modal="true" aria-labelledby="segment-title"><header><div><span>توزيع ساعات العمل</span><h3 id="segment-title">${editing?"تعديل فترة العمل":"إضافة فترة عمل جديدة"}</h3></div><button type="button" class="modal-close" aria-label="إغلاق">×</button></header><form id="segment-form"><div class="time-grid"><label>من الساعة${timePicker("segment-from",segment.from)}</label><span>←</span><label>إلى الساعة${timePicker("segment-to",segment.to)}</label></div><div class="modal-duration">مدة الفترة: <b id="segment-duration">${formatHours(durationHours(segment.from,segment.to))} ساعات</b></div><div class="tasks-head"><label>مهام العمل</label><button type="button" id="add-task" class="mini-add">＋ مهمة إضافية</button></div><div id="tasks-list">${segment.tasks.map((task,i)=>taskInput(task,i)).join("")}</div><p id="segment-error" class="form-message error hidden"></p><footer>${editing?'<button type="button" id="delete-segment" class="danger-btn">حذف الفترة</button>':'<span></span>'}<div><button type="button" class="secondary modal-cancel">إلغاء</button><button class="primary">${editing?"حفظ التعديلات":"إضافة إلى توزيع المهام"}</button></div></footer></form></section></div>`;
  const close=()=>{$("#modal-root").innerHTML="";};$(".modal-close").onclick=$(".modal-cancel").onclick=close;$(".modal-backdrop").onclick=e=>{if(e.target.classList.contains("modal-backdrop"))close();};$("#add-task").onclick=()=>{$("#tasks-list").insertAdjacentHTML("beforeend",taskInput("",$("#tasks-list").children.length));bindTaskRemovers();};bindTaskRemovers();const updateDuration=()=>{$("#segment-duration").textContent=`${formatHours(durationHours(timeValue("segment-from"),timeValue("segment-to")))} ساعات`;};document.querySelectorAll(".custom-time-picker select").forEach(select=>select.onchange=updateDuration);
  if(editing)$("#delete-segment").onclick=()=>{state.draftSegments.splice(editIndex,1);close();renderTimeline();};
  $("#segment-form").onsubmit=e=>{e.preventDefault();const from=timeValue("segment-from"),to=timeValue("segment-to"),hours=durationHours(from,to),tasks=[...document.querySelectorAll('.task-input input')].map(x=>x.value.trim()).filter(Boolean),total=Number($("#daily-hours").value),otherUsed=state.draftSegments.reduce((sum,s,i)=>sum+(i===editIndex?0:s.hours),0);if(!tasks.length)return segmentError("أضف مهمة عمل واحدة على الأقل.");if(otherUsed+hours>total+0.001)return segmentError(`مدة الفترة أكبر من الساعات المتبقية (${formatHours(total-otherUsed)} ساعات).`);const record={from,to,hours,tasks};if(editing)state.draftSegments[editIndex]=record;else state.draftSegments.push(record);close();renderTimeline();};
}
function taskInput(value,index){return `<div class="task-input"><span>${index+1}</span><input value="${escapeHtml(value)}" placeholder="اكتب مهمة العمل" required>${index?'<button type="button" aria-label="حذف المهمة">×</button>':'<i></i>'}</div>`;}
function bindTaskRemovers(){document.querySelectorAll(".task-input button").forEach(button=>button.onclick=()=>{button.parentElement.remove();document.querySelectorAll(".task-input").forEach((row,i)=>row.querySelector("span").textContent=i+1);});}
function segmentError(message){const el=$("#segment-error");el.textContent=message;el.classList.remove("hidden");}

async function saveEmployee(event){
  event.preventDefault();const form=event.target,button=event.submitter,data=Object.fromEntries(new FormData(form)),dailyHours=Number(data.dailyHours),attendancePin=onlyDigits(data.attendancePin),primaryNumber=onlyDigits(data.primaryPhone);
  if(!form.checkValidity()){form.reportValidity();return showError("يرجى إكمال جميع الحقول المطلوبة.");}
  if(attendancePin.length<4||attendancePin.length>8)return showError("رمز دخول البصمة يجب أن يتكون من 4 إلى 8 أرقام.");
  if(!dailyHours||dailyHours>24)return showError("أدخل عدد ساعات عمل صحيحًا من 1 إلى 24.");
  if(data.nationality&&!supportedCountries.some(country=>country[0]===data.nationality))return showError("اختر جنسية من قائمة الجنسيات المتاحة أو اترك الحقل فارغاً.");
  if(primaryNumber&&data.primaryDial==="+965"&&primaryNumber.length!==8)return showError("رقم الهاتف الشخصي الكويتي يجب أن يتكون من 8 أرقام.");
  if(primaryNumber&&data.primaryDial!=="+965"&&(primaryNumber.length<6||primaryNumber.length>15))return showError("أدخل رقم هاتف شخصي صحيحاً أو اترك الحقل فارغاً.");
  if(state.employees.some(employee=>String(employee.attendancePin||"")===attendancePin))return showError("رمز دخول البصمة مستخدم لموظف آخر، اختر رمزًا مختلفًا.");
  button.disabled=true;const id=crypto.randomUUID(),pinRef=ref(db,`organizations/default/attendancePins/${attendancePin}`);let pinReserved=false,photoDataUrl="";$("#action-loading").classList.remove("hidden");
  try{if(!state.demo&&state.user){const reservation=await runTransaction(pinRef,current=>current===null?id:undefined,{applyLocally:false});if(!reservation.committed)throw new Error("رمز دخول البصمة مستخدم لموظف آخر، اختر رمزًا مختلفًا.");pinReserved=true;}const file=$("#photo").files[0];if(file)photoDataUrl=await readEmployeePhoto(file);const alternatePhones=[...form.querySelectorAll(".alternate-phone-row")].map(row=>({phone:onlyDigits(row.querySelector('[name="alternatePhone"]').value),dialCode:row.querySelector('[name="alternateDial"]').value,country:countryByDial(row.querySelector('[name="alternateDial"]').value)[0]})).filter(item=>item.phone);const relatives=[...form.querySelectorAll(".relative-row")].map(row=>({phone:onlyDigits(row.querySelector('[name="relativePhone"]').value),dialCode:row.querySelector('[name="relativeDial"]').value,country:countryByDial(row.querySelector('[name="relativeDial"]').value)[0],relation:row.querySelector('[name="relation"]').value.trim()})).filter(item=>item.phone);const record={id,fullName:data.fullName.trim(),civilId:onlyDigits(data.civilId),nationality:data.nationality||"",jobTitle:data.jobTitle.trim(),workEntity:data.workEntity,attendancePin,dailyHours,scheduleType:data.scheduleType,segments:data.scheduleType==="fixed"?[...state.draftSegments]:[],primaryPhone:primaryNumber?{phone:primaryNumber,dialCode:data.primaryDial,country:countryByDial(data.primaryDial)[0]}:null,alternatePhones,relatives,photoUrl:"",photoDataUrl,profileCompleted:false,createdAt:Date.now()};if(state.demo||!state.user)state.employees.unshift(record);else await set(ref(db,`organizations/default/employees/${id}`),record);await sleep(1200);$("#action-loading").classList.add("hidden");showToast(`تم إدراج الموظف ${record.fullName} وربط رمز البصمة بنجاح`);state.page="employees";renderNav();renderPage();}catch(error){if(pinReserved)await remove(pinRef).catch(()=>{});$("#action-loading").classList.add("hidden");showError(error.message||"تعذر إدراج الموظف");button.disabled=false;}
}

const arabicWeekdays=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
const localDateKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const dateFromKey=key=>{const [year,month,day]=String(key).split("-").map(Number);return new Date(year,month-1,day,12);};
const leaveTypeLabel=leave=>leave?.type==="weekly"?"إجازة أسبوعية":leave?.type==="sick"?"إجازة مرضية":leave?.type==="annual"?"إجازة سنوية":"إجازة";
const leaveDateText=key=>{const date=dateFromKey(key);return `${arabicWeekdays[date.getDay()]} ${date.getDate()}-${date.getMonth()+1}-${date.getFullYear()}`;};
function currentWeekDates(){const now=new Date(),start=new Date(now);start.setHours(12,0,0,0);start.setDate(now.getDate()-((now.getDay()-6+7)%7));return Array.from({length:7},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return{key:localDateKey(date),name:arabicWeekdays[date.getDay()],date};});}
function leaveForEmployeeToday(employeeId){const today=localDateKey(new Date());return state.leaves.find(leave=>leave.employeeId===employeeId&&leave.startDate<=today&&leave.endDate>=today);}
function employeeLeaveSummary(employee){const leave=leaveForEmployeeToday(employee.id);return leave?`<span class="leave-current-status ${leave.duration==="half"?"half":"full"}">${escapeHtml(leaveTypeLabel(leave))}${leave.duration==="half"?" · نصف يوم":""}</span>`:"";}
function calculateLeaveEnd(startDate,totalDays,skipDay){let date=dateFromKey(startDate),remaining=Math.max(1,Math.round(Number(totalDays)||1));while(remaining>0){if(skipDay===null||date.getDay()!==Number(skipDay))remaining--;if(remaining===0)return localDateKey(date);date.setDate(date.getDate()+1);}return startDate;}
function leaveWeeksOptions(selected=""){return currentWeekDates().map(day=>`<option value="${day.key}" ${day.key===selected?"selected":""}>${day.name} · ${leaveDateText(day.key)}</option>`).join("");}
function weekdayOptions(selected=5){return arabicWeekdays.map((day,index)=>`<option value="${index}" ${Number(selected)===index?"selected":""}>${day}</option>`).join("");}

function renderLeaves(){
  const employees=[...state.employees].sort((a,b)=>String(a.fullName||"").localeCompare(String(b.fullName||""),"ar"));
  $("#page-content").innerHTML=`<section class="leaves-page"><div class="leaves-heading"><div><span class="eyebrow">إدارة الإجازات</span><h1>إجازات الموظفين</h1></div><span>${employees.length} موظف</span></div><section class="leaves-list-card"><header><div><h2>قائمة الموظفين</h2></div><i>⌁</i></header><div class="leave-employees-grid">${employees.length?employees.map(employee=>`<article class="leave-employee"><div class="leave-person"><span class="leave-avatar">${employeePhotoSrc(employee)?`<img src="${escapeHtml(employeePhotoSrc(employee))}" alt="">`:initials(employee.fullName)}</span><div><b>${escapeHtml(employee.fullName)}</b><small>${escapeHtml(employee.jobTitle||"المسمى الوظيفي غير محدد")}</small>${employeeLeaveSummary(employee)}</div></div><div class="leave-actions"><button class="weekly-leave-button" data-weekly-leave="${escapeHtml(employee.id)}"><i>＋</i> إجازة أسبوعية</button><button class="special-leave-button" data-special-leave="${escapeHtml(employee.id)}">إجازة خاصة</button></div></article>`).join(""):'<div class="empty"><b>لا يوجد موظفون بعد</b></div>'}</div></section></section>`;
  document.querySelectorAll("[data-weekly-leave]").forEach(button=>button.onclick=()=>openWeeklyLeaveModal(button.dataset.weeklyLeave));
  document.querySelectorAll("[data-special-leave]").forEach(button=>button.onclick=()=>openSpecialLeaveModal(button.dataset.specialLeave));
}

function closeLeaveModal(){ $("#modal-root").innerHTML=""; }
function bindLeaveModalClose(backdropClass){const root=$("#modal-root");root.querySelector(".modal-close").onclick=closeLeaveModal;root.querySelectorAll(".modal-cancel").forEach(button=>button.onclick=closeLeaveModal);root.querySelector(`.${backdropClass}`).onclick=event=>{if(event.target.classList.contains(backdropClass))closeLeaveModal();};}
async function saveLeave(record,employee){
  const root=$("#modal-root");
  root.innerHTML=`<div class="leave-saving-loading" role="status" aria-live="polite"><section><div class="leave-save-orbit"><i></i><i></i><span>✓</span></div><span>إدارة الإجازات</span><h2>جارٍ اعتماد الإجازة...</h2><div><i></i><i></i><i></i></div></section></div>`;
  try{await sleep(2000);if(state.demo){state.leaves=[record,...state.leaves];}else await set(ref(db,`organizations/default/leaves/${record.id}`),record);root.innerHTML="";showToast(`تم اعتماد ${leaveTypeLabel(record)} للموظف ${employee.fullName}`);if(state.demo)renderLeaves();}catch(error){root.innerHTML="";showToast(error.message||"تعذر حفظ الإجازة، حاول مرة أخرى.");}
}

function openWeeklyLeaveModal(employeeId){
  const employee=state.employees.find(item=>item.id===employeeId);if(!employee)return;
  const root=$("#modal-root"),firstDay=currentWeekDates()[0]?.key||localDateKey(new Date());
  root.innerHTML=`<div class="modal-backdrop leave-modal-backdrop"><section class="modal leave-modal" role="dialog" aria-modal="true" aria-labelledby="weekly-leave-title"><header><div><span>إجازة أسبوعية</span><h3 id="weekly-leave-title">إجازة ${escapeHtml(employee.fullName)}</h3></div><button type="button" class="modal-close" aria-label="إغلاق">×</button></header><form id="weekly-leave-form" class="leave-form"><fieldset class="leave-duration-choice"><legend>نوع الإجازة</legend><label><input type="radio" name="weeklyDuration" value="full" checked><span><b>يوم كامل</b></span></label><label><input type="radio" name="weeklyDuration" value="half"><span><b>نصف يوم</b></span></label></fieldset><label>اختر يوم الإجازة<select id="weekly-leave-date">${leaveWeeksOptions(firstDay)}</select></label><footer><span></span><div><button type="button" class="secondary modal-cancel">إلغاء</button><button class="primary">اعتماد الإجازة</button></div></footer></form></section></div>`;
  bindLeaveModalClose("leave-modal-backdrop");
  $("#weekly-leave-form").onsubmit=event=>{event.preventDefault();const startDate=$("#weekly-leave-date").value,duration=root.querySelector('[name="weeklyDuration"]:checked').value;saveLeave({id:crypto.randomUUID(),employeeId:employee.id,type:"weekly",duration,startDate,endDate:startDate,leaveDays:duration==="half"?.5:1,createdAt:Date.now()},employee);};
}

function openSpecialLeaveModal(employeeId){
  const employee=state.employees.find(item=>item.id===employeeId);if(!employee)return;
  const root=$("#modal-root");
  root.innerHTML=`<div class="modal-backdrop leave-modal-backdrop"><section class="modal leave-modal" role="dialog" aria-modal="true" aria-labelledby="special-leave-title"><header><div><span>إجازة خاصة</span><h3 id="special-leave-title">إجازة ${escapeHtml(employee.fullName)}</h3></div><button type="button" class="modal-close" aria-label="إغلاق">×</button></header><form id="special-leave-start" class="leave-form"><div class="leave-form-grid"><label>نوع الإجازة<select id="special-leave-type"><option value="sick">مرضية</option><option value="annual">سنوية</option></select></label><label>فترة الإجازة<div class="leave-period-field"><input id="special-leave-period" class="english-number decimal-number" inputmode="decimal" value="1" placeholder="2.5" required><select id="special-leave-unit"><option value="days">يوم</option><option value="months">شهر</option></select></div></label></div><p id="special-leave-error" class="form-message error hidden"></p><footer><span></span><div><button type="button" class="secondary modal-cancel">إلغاء</button><button class="primary">التالي</button></div></footer></form></section></div>`;
  bindLeaveModalClose("leave-modal-backdrop");bindEnglishNumbers(root);
  $("#special-leave-start").onsubmit=event=>{event.preventDefault();const value=Number($("#special-leave-period").value),error=$("#special-leave-error");if(!value||value<=0){error.textContent="اكتب مدة الإجازة بصورة صحيحة.";error.classList.remove("hidden");return;}openSpecialLeaveDateStep(employee,{type:$("#special-leave-type").value,value,unit:$("#special-leave-unit").value});};
}

function openSpecialLeaveDateStep(employee,details){
  const root=$("#modal-root"),defaultStart=localDateKey(new Date()),totalDays=details.unit==="months"?details.value*30:details.value;
  root.innerHTML=`<div class="modal-backdrop leave-modal-backdrop"><section class="modal leave-modal" role="dialog" aria-modal="true" aria-labelledby="special-date-title"><header><div><span>${details.type==="sick"?"إجازة مرضية":"إجازة سنوية"}</span><h3 id="special-date-title">تحديد فترة الإجازة</h3></div><button type="button" class="modal-close" aria-label="إغلاق">×</button></header><form id="special-leave-date-form" class="leave-form"><label>تاريخ بدء الإجازة<input id="special-leave-start-date" type="date" value="${defaultStart}" required></label><div class="leave-date-preview"><b>بداية الإجازة</b><span id="leave-start-preview"></span></div><label id="skip-weekday-line" class="leave-skip-line"><input id="skip-weekday-enabled" type="checkbox" checked><span>تخطي أيام <select id="skip-weekday">${weekdayOptions(5)}</select> من الحساب</span></label><div class="leave-date-preview end"><b>تاريخ انتهاء الإجازة</b><span id="leave-end-preview"></span></div><footer><span></span><div><button type="button" class="secondary modal-cancel">إلغاء</button><button class="primary">اعتماد الإجازة</button></div></footer></form></section></div>`;
  bindLeaveModalClose("leave-modal-backdrop");
  const updatePreview=()=>{const startDate=$("#special-leave-start-date").value||defaultStart,skipEnabled=$("#skip-weekday-enabled").checked,skipDay=skipEnabled?Number($("#skip-weekday").value):null,endDate=calculateLeaveEnd(startDate,totalDays,skipDay);$("#leave-start-preview").textContent=leaveDateText(startDate);$("#leave-end-preview").textContent=leaveDateText(endDate);$("#skip-weekday-line").classList.toggle("disabled",!skipEnabled);return{startDate,endDate,skipDay};};
  $("#special-leave-start-date").onchange=updatePreview;$("#skip-weekday").onchange=updatePreview;$("#skip-weekday-enabled").onchange=updatePreview;updatePreview();
  $("#special-leave-date-form").onsubmit=event=>{event.preventDefault();const dates=updatePreview();saveLeave({id:crypto.randomUUID(),employeeId:employee.id,type:details.type,duration:"full",startDate:dates.startDate,endDate:dates.endDate,leaveDays:Math.round(totalDays),skipWeekday:dates.skipDay,skipEnabled:$("#skip-weekday-enabled").checked,durationValue:details.value,durationUnit:details.unit,createdAt:Date.now()},employee);};
}

function renderEntities(){$("#page-content").innerHTML=`${hero("جهات العمل","أنشئ الفروع والإدارات التي يُسند إليها الموظفون.",'<form id="entity-form" class="entity-form"><input id="entity-name" placeholder="اسم الإدارة أو الفرع"><button class="primary">＋ إضافة جهة</button></form>')}<div class="entities">${state.entities.map((e,i)=>`<article><i style="background:${["#0f766e","#c6923f","#2563eb"][i%3]}">▥</i><div><h3>${escapeHtml(e)}</h3><p>${state.employees.filter(x=>x.workEntity===e).length} موظفين</p></div></article>`).join("")}</div>`;$("#entity-form").onsubmit=async e=>{e.preventDefault();const name=$("#entity-name").value.trim();if(!name)return;state.entities.push(name);if(state.user&&!state.demo)await set(push(ref(db,"organizations/default/workEntities")),name);showToast(`تمت إضافة ${name}`);renderEntities();};}
function renderSchedules(){renderScheduleWorkspace({container:$("#page-content"),state,db,ref,get,set,CONFIG,showToast,escapeHtml});}
function renderSettings(){const logo=state.settings.companyLogoUrl||state.settings.companyLogoDataUrl;$("#page-content").innerHTML=`<section class="settings-page"><div class="settings-heading"><span class="eyebrow">هوية المنشأة</span><h1>إعدادات المنشأة</h1></div><section class="company-logo-setting"><div><span class="settings-index">01</span><h2>شعار المنشأة</h2></div><label class="company-logo-upload ${logo?"has-logo":""}" for="company-logo-input"><input id="company-logo-input" type="file" accept="image/png"><span class="company-logo-preview">${logo?`<img src="${escapeHtml(logo)}" alt="شعار المنشأة">`:'<i>▧</i>'}</span><b>${logo?"تغيير شعار المنشأة":"رفع شعار PNG"}</b></label><p id="company-logo-status" class="settings-status"></p></section></section>`;$("#company-logo-input").onchange=async event=>{const file=event.target.files?.[0];let status=$("#company-logo-status");if(!file)return;if(file.type!=="image/png"){status.textContent="يرجى اختيار ملف PNG فقط.";status.className="settings-status error";event.target.value="";return;}if(file.size>1024*1024){status.textContent="اجعل حجم الشعار أقل من 1 ميغابايت.";status.className="settings-status error";event.target.value="";return;}const previousSettings={...state.settings};status.textContent="جارٍ حفظ الشعار...";status.className="settings-status";try{const companyLogoDataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("تعذر قراءة ملف الشعار"));reader.readAsDataURL(file);});state.settings={...state.settings,companyLogoDataUrl,companyLogoUrl:""};if(!state.demo&&state.user)await set(ref(db,"organizations/default/settings"),{...state.settings,updatedAt:Date.now()});renderSettings();showToast("تم حفظ شعار المنشأة");}catch(error){state.settings=previousSettings;renderSettings();const message=$("#company-logo-status");message.textContent=error.message||"تعذر حفظ الشعار، حاول مرة أخرى.";message.className="settings-status error";}};}
function renderGeneric(label){$("#page-content").innerHTML=`${hero(label,`مساحة منظمة لإنشاء ومراجعة واعتماد ${label}.`,'<button class="primary">＋ إنشاء جديد</button>')}<div class="kpis"><article><i>▤</i><div><small>إجمالي السجلات</small><b>24</b></div></article><article><i>◷</i><div><small>بانتظار الاعتماد</small><b>6</b></div></article><article><i>✓</i><div><small>مكتمل</small><b>18</b></div></article></div><div class="documents"><h3>أحدث السجلات</h3>${["اعتماد تحديث السياسات الداخلية","مراجعة بيانات الحضور الشهرية","تعميم تنظيم الإجازات"].map((x,i)=>`<div><i>▤</i><span><b>${x}</b><small>الإدارة العامة · منذ ${i+1} أيام</small></span><em>${i===1?"قيد المراجعة":"معتمد"}</em></div>`).join("")}</div>`;}

function localToday(){return localDateKey(new Date());}
function attendanceTime(timestamp){if(!timestamp)return"—";return new Date(Number(timestamp)).toLocaleTimeString("ar-KW",{hour:"2-digit",minute:"2-digit",hour12:true});}
function attendanceDate(date){return leaveDateText(date);}
function durationText(minutes){if(!Number.isFinite(minutes)||minutes<=0)return"—";return`${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(Math.round(minutes%60)).padStart(2,"0")}`;}
function scheduleBounds(date,employeeId){const assignments=Object.values(state.schedules?.[date]?.assignments||{}).filter(item=>item.employeeId===employeeId&&item.from&&item.to);if(!assignments.length)return null;const from=Math.min(...assignments.map(item=>{const [h,m]=String(item.from).split(":").map(Number);return h*60+m;})),to=Math.max(...assignments.map(item=>{const [h,m]=String(item.to).split(":").map(Number);return h*60+m;}));return{from,to};}
function minutesOf(timestamp){const date=new Date(Number(timestamp));return date.getHours()*60+date.getMinutes();}
function attendanceRows(filter=state.attendanceFilter||{}){const start=filter.startDate||localToday(),end=filter.endDate||localToday(),employeeId=filter.employeeId||"";const rows=[];Object.entries(state.attendance||{}).forEach(([date,employeeLogs])=>{if(date<start||date>end)return;Object.entries(employeeLogs||{}).forEach(([id,logs])=>{if(employeeId&&id!==employeeId)return;const events=Object.values(logs||{}).filter(Boolean).sort((a,b)=>Number(a.timestamp||0)-Number(b.timestamp||0));if(!events.length)return;const checkIn=events.find(item=>item.type==="checkIn")||null,checkOut=[...events].reverse().find(item=>item.type==="checkOut")||null,bounds=scheduleBounds(date,id),inMinutes=checkIn?minutesOf(checkIn.timestamp):null,outMinutes=checkOut?minutesOf(checkOut.timestamp):null;rows.push({date,employeeId:id,employee:state.employees.find(item=>item.id===id),checkIn,checkOut,firstTimestamp:Number(events[0].timestamp||0),late:bounds&&inMinutes!==null?Math.max(0,inMinutes-bounds.from):0,early:bounds&&outMinutes!==null?Math.max(0,bounds.to-outMinutes):0,lateOut:bounds&&outMinutes!==null?Math.max(0,outMinutes-bounds.to):0,place:checkIn?.branchName||checkOut?.branchName||""});});});return rows.sort((a,b)=>a.firstTimestamp-b.firstTimestamp);}
function attendanceTable(rows){return rows.length?`<div class="attendance-table-wrap"><table class="attendance-table"><thead><tr><th>اسم الموظف</th><th>التاريخ</th><th>وقت الدخول</th><th>وقت الخروج</th><th>تأخير</th><th>خروج مبكر</th><th>خروج متأخر</th></tr></thead><tbody>${rows.map(row=>`<tr><td><b>${escapeHtml(row.employee?.fullName||"موظف غير معروف")}</b>${row.place?`<small>${escapeHtml(row.place)}</small>`:""}</td><td>${attendanceDate(row.date)}</td><td>${attendanceTime(row.checkIn?.timestamp)}</td><td>${attendanceTime(row.checkOut?.timestamp)}</td><td class="${row.late?"metric-warn":""}">${durationText(row.late)}</td><td class="${row.early?"metric-warn":""}">${durationText(row.early)}</td><td class="${row.lateOut?"metric-good":""}">${durationText(row.lateOut)}</td></tr>`).join("")}</tbody></table></div>`:`<div class="attendance-empty"><i>◷</i><b>لا توجد بصمات ضمن الفترة المحددة</b></div>`;}
function reportFilters(){return state.attendanceFilter||{employeeId:"",startDate:localToday(),endDate:localToday()};}
function renderAttendanceReport(){const filter=reportFilters();state.attendanceFilter=filter;$("#page-content").innerHTML=`<section class="attendance-report"><div class="attendance-report-head"><div><span class="eyebrow">الحضور والانصراف</span><h1>تقرير البصمة</h1></div><div class="attendance-export-actions"><button id="attendance-excel" class="secondary">تحميل Excel</button><button id="attendance-pdf" class="primary">تحميل PDF</button></div></div><section class="attendance-filters"><label>الموظف<select id="attendance-employee"><option value="">جميع الموظفين</option>${state.employees.map(employee=>`<option value="${escapeHtml(employee.id)}" ${filter.employeeId===employee.id?"selected":""}>${escapeHtml(employee.fullName)}</option>`).join("")}</select></label><label>من تاريخ<input id="attendance-start" type="date" value="${filter.startDate}"></label><label>إلى تاريخ<input id="attendance-end" type="date" value="${filter.endDate}"></label><button id="attendance-apply" class="primary">عرض التقرير</button></section><section id="attendance-report-body" class="attendance-report-body"><div class="attendance-loader"><div><i></i><i></i><i></i></div><b>جاري جلب بيانات البصمة لليوم...</b><span>نرتب عمليات الحضور من الأقدم إلى الأحدث</span></div></section></section>`;$("#attendance-apply").onclick=applyAttendanceFilter;$("#attendance-excel").onclick=exportAttendanceExcel;$("#attendance-pdf").onclick=exportAttendancePdf;clearTimeout(attendanceRenderTimer);attendanceRenderTimer=setTimeout(refreshAttendanceReport,650);}
function applyAttendanceFilter(){const startDate=$("#attendance-start").value||localToday(),endDate=$("#attendance-end").value||startDate;if(endDate<startDate){showToast("تاريخ النهاية يجب أن يكون بعد تاريخ البداية.");return;}state.attendanceFilter={employeeId:$("#attendance-employee").value,startDate,endDate};refreshAttendanceReport();}
function refreshAttendanceReport(){const body=$("#attendance-report-body");if(!body)return;const rows=attendanceRows();body.innerHTML=`<div class="attendance-summary"><span>عدد الموظفين الذين بصموا: <b>${rows.length}</b></span><span>الفترة: <b>${attendanceDate(state.attendanceFilter.startDate)} — ${attendanceDate(state.attendanceFilter.endDate)}</b></span></div>${attendanceTable(rows)}`;}
function excelRows(rows){return rows.map(row=>({"اسم الموظف":row.employee?.fullName||"موظف غير معروف","التاريخ":attendanceDate(row.date),"وقت الدخول":attendanceTime(row.checkIn?.timestamp),"وقت الخروج":attendanceTime(row.checkOut?.timestamp),"تأخير":durationText(row.late),"خروج مبكر":durationText(row.early),"خروج متأخر":durationText(row.lateOut)}));}
function exportAttendanceExcel(){const rows=attendanceRows();if(!rows.length){showToast("لا توجد بيانات لتصديرها.");return;}const data=excelRows(rows);if(window.XLSX){const sheet=window.XLSX.utils.json_to_sheet(data),workbook=window.XLSX.utils.book_new();window.XLSX.utils.book_append_sheet(workbook,sheet,"تقرير البصمة");window.XLSX.writeFile(workbook,`تقرير البصمة ${state.attendanceFilter.startDate} - ${state.attendanceFilter.endDate}.xlsx`);return;}const header=Object.keys(data[0]),csv="\ufeff"+[header,...data.map(row=>header.map(key=>`\"${String(row[key]).replaceAll('"','""')}\"`).join(","))].join("\n"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`تقرير البصمة ${state.attendanceFilter.startDate}.csv`;link.click();URL.revokeObjectURL(url);}
function reportLogos(){const company=state.settings.companyLogoUrl||state.settings.companyLogoDataUrl;return`<div class="attendance-pdf-logos"><span>${company?`<img src="${escapeHtml(company)}" crossorigin="anonymous" alt="شعار المنشأة">`:""}</span><img src="rakaez-mark.png" crossorigin="anonymous" alt="شعار ركائز"></div>`;}
async function exportAttendancePdf(){const rows=attendanceRows();if(!rows.length){showToast("لا توجد بيانات لتصديرها.");return;}if(!window.html2canvas||!window.jspdf){showToast("تعذر تجهيز ملف PDF، أعد المحاولة بعد اكتمال تحميل الصفحة.");return;}const root=document.createElement("div");root.className="attendance-pdf-render";root.innerHTML=`${reportLogos()}<h1>تقرير البصمة</h1><p>${attendanceDate(state.attendanceFilter.startDate)} — ${attendanceDate(state.attendanceFilter.endDate)}</p>${attendanceTable(rows)}`;document.body.append(root);try{const canvas=await window.html2canvas(root,{scale:2,backgroundColor:"#fff",useCORS:true}),{jsPDF}=window.jspdf,pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});pdf.addImage(canvas.toDataURL("image/png"),"PNG",0,0,297,210);pdf.save(`تقرير البصمة ${state.attendanceFilter.startDate} - ${state.attendanceFilter.endDate}.pdf`);}finally{root.remove();}}

function renderSettings(){const logo=state.settings.companyLogoUrl||state.settings.companyLogoDataUrl;$("#page-content").innerHTML=`<section class="settings-page"><div class="settings-heading"><span class="eyebrow">إعدادات المنشأة</span><h1>إعدادات المنشأة</h1></div><section class="company-logo-setting"><div><span class="settings-index">01</span><h2>شعار المنشأة</h2></div><label class="company-logo-upload ${logo?"has-logo":""}" for="company-logo-input"><input id="company-logo-input" type="file" accept="image/png"><span class="company-logo-preview">${logo?`<img src="${escapeHtml(logo)}" alt="شعار المنشأة">`:'<i>▧</i>'}</span><b>${logo?"تغيير شعار المنشأة":"رفع شعار PNG"}</b></label><p id="company-logo-status" class="settings-status"></p></section><section class="fingerprint-settings-link"><div><span class="settings-index">02</span><h2>أماكن البصمة</h2><p>إدارة الباركود والإحداثيات ونطاق التحقق.</p></div><button id="open-fingerprint-places" class="primary">إدارة أماكن البصمة</button></section></section>`;$("#open-fingerprint-places").onclick=()=>{state.page="fingerprint-places";renderPage();};$("#company-logo-input").onchange=saveCompanyLogo;}
async function saveCompanyLogo(event){const file=event.target.files?.[0],status=$("#company-logo-status");if(!file)return;if(file.type!=="image/png"){status.textContent="يرجى اختيار ملف PNG فقط.";status.className="settings-status error";return;}if(file.size>1024*1024){status.textContent="اجعل حجم الشعار أقل من 1 ميغابايت.";status.className="settings-status error";return;}try{const companyLogoDataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("تعذر قراءة ملف الشعار"));reader.readAsDataURL(file);});state.settings={...state.settings,companyLogoDataUrl,companyLogoUrl:""};if(!state.demo&&state.user)await set(ref(db,"organizations/default/settings"),{...state.settings,updatedAt:Date.now()});showToast("تم حفظ شعار المنشأة");renderSettings();}catch(error){status.textContent=error.message||"تعذر حفظ الشعار.";status.className="settings-status error";}}
function placeCard(place){const location=place.location||{},coordinates=Number.isFinite(Number(location.lat))&&Number.isFinite(Number(location.lng))?`${Number(location.lat).toFixed(6)}, ${Number(location.lng).toFixed(6)}`:"غير محددة";return`<article class="fingerprint-place-card"><div><span>مكان البصمة</span><h3>${escapeHtml(place.title||place.branchName||"مكان بلا اسم")}</h3><p>${escapeHtml(place.branchName||place.branchKey||"")}</p></div><dl><div><dt>الباركود</dt><dd>${escapeHtml(place.barcodeValue||place.barcodeToken||"—")}</dd></div><div><dt>الإحداثيات</dt><dd>${coordinates}</dd></div><div><dt>النطاق</dt><dd>${escapeHtml(place.radiusMeters||"—")} متر</dd></div></dl><button data-edit-place="${escapeHtml(place.id)}" class="secondary">تعديل</button></article>`;}
function renderFingerprintPlaces(){$("#page-content").innerHTML=`<section class="fingerprint-places-page"><div class="attendance-report-head"><div><span class="eyebrow">إعدادات البصمة</span><h1>أماكن البصمة</h1></div><div><button id="back-settings" class="secondary">→ الإعدادات</button><button id="add-fingerprint-place" class="primary">＋ إضافة مكان</button></div></div><section class="fingerprint-places-grid">${state.fingerprintPlaces.length?state.fingerprintPlaces.map(placeCard).join(""):'<div class="attendance-empty"><b>لا توجد أماكن بصمة بعد</b></div>'}</section></section>`;$("#back-settings").onclick=()=>{state.page="settings";renderPage();};$("#add-fingerprint-place").onclick=()=>openFingerprintPlaceModal();document.querySelectorAll("[data-edit-place]").forEach(button=>button.onclick=()=>openFingerprintPlaceModal(button.dataset.editPlace));}
function fingerprintPlaceForm(place={}){const location=place.location||{};return`<div class="modal-backdrop"><section class="modal fingerprint-place-modal"><header><div><span>أماكن البصمة</span><h3>${place.id?"تعديل مكان البصمة":"إضافة مكان بصمة"}</h3></div><button type="button" class="modal-close">×</button></header><form id="fingerprint-place-form"><div class="editor-grid"><label>اسم المكان<input name="title" value="${escapeHtml(place.title||"")}" required></label><label>الفرع<select name="branchKey"><option value="hawalli" ${["hawalli","surra"].includes(place.branchKey)?"selected":""}>حولي</option><option value="abu_al_hasaniya" ${["abu_al_hasaniya","abulhasania"].includes(place.branchKey)?"selected":""}>أبو الحصانية</option><option value="yarmouk" ${place.branchKey==="yarmouk"?"selected":""}>اليرموك</option></select></label><label class="wide-field">قيمة الباركود<input name="barcodeValue" dir="ltr" value="${escapeHtml(place.barcodeValue||"")}" required></label><label>خط العرض<input name="latitude" dir="ltr" inputmode="decimal" value="${escapeHtml(location.lat||"")}" required></label><label>خط الطول<input name="longitude" dir="ltr" inputmode="decimal" value="${escapeHtml(location.lng||"")}" required></label><label>النطاق بالمتر<input name="radiusMeters" inputmode="numeric" value="${escapeHtml(place.radiusMeters||30)}" required></label></div><p id="fingerprint-place-error" class="form-message error hidden"></p><footer><button type="button" class="secondary modal-cancel">إلغاء</button><button class="primary">حفظ المكان</button></footer></form></section></div>`;}
function openFingerprintPlaceModal(id=""){const place=state.fingerprintPlaces.find(item=>item.id===id)||{},root=$("#modal-root");root.innerHTML=fingerprintPlaceForm(place);const close=()=>root.innerHTML="";$(".modal-close").onclick=$(".modal-cancel").onclick=close;$("#fingerprint-place-form").onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target)),branchName={hawalli:"حولي",abu_al_hasaniya:"أبو الحصانية",yarmouk:"اليرموك"}[data.branchKey],barcodeValue=data.barcodeValue.trim(),barcodeToken=barcodeValue.startsWith("HRMS-BASMA:")?barcodeValue.slice("HRMS-BASMA:".length):barcodeValue,error=$("#fingerprint-place-error");if(!Number.isFinite(Number(data.latitude))||!Number.isFinite(Number(data.longitude))||Number(data.radiusMeters)<=0){error.textContent="تحقق من الإحداثيات والنطاق.";error.classList.remove("hidden");return;}const record={...place,id:place.id||crypto.randomUUID(),mode:"barcode",title:data.title.trim(),branchKey:data.branchKey,branchName,barcodeValue,barcodeToken,location:{lat:Number(data.latitude),lng:Number(data.longitude)},radiusMeters:Number(data.radiusMeters),updatedAt:Date.now()};try{await set(ref(db,`organizations/default/fingerprintPlaces/${record.id}`),record);close();showToast("تم حفظ مكان البصمة");}catch(err){error.textContent=err.message||"تعذر حفظ المكان.";error.classList.remove("hidden");}};}

function renderFingerprintPlaces(){const importButton=!state.fingerprintPlaces.length?'<button id="import-legacy-places" class="secondary">نقل الأماكن والباركودات الأصلية</button>':"";$("#page-content").innerHTML=`<section class="fingerprint-places-page"><div class="attendance-report-head"><div><span class="eyebrow">إعدادات البصمة</span><h1>أماكن البصمة</h1></div><div><button id="back-settings" class="secondary">→ الإعدادات</button>${importButton}<button id="add-fingerprint-place" class="primary">＋ إضافة مكان</button></div></div><section class="fingerprint-places-grid">${state.fingerprintPlaces.length?state.fingerprintPlaces.map(placeCard).join(""):'<div class="attendance-empty"><b>لا توجد أماكن بصمة بعد</b></div>'}</section></section>`;$("#back-settings").onclick=()=>{state.page="settings";renderPage();};$("#add-fingerprint-place").onclick=()=>openFingerprintPlaceModal();$("#import-legacy-places")&&( $("#import-legacy-places").onclick=migrateLegacyFingerprintPlaces );document.querySelectorAll("[data-edit-place]").forEach(button=>button.onclick=()=>openFingerprintPlaceModal(button.dataset.editPlace));}
async function migrateLegacyFingerprintPlaces(){const button=$("#import-legacy-places");if(button){button.disabled=true;button.textContent="جاري النقل...";}try{await set(ref(db,"organizations/default/fingerprintPlaces"),LEGACY_FINGERPRINT_PLACES);showToast("تم نقل أماكن البصمة والباركودات الأصلية إلى ركائز");}catch(error){showToast(error.message||"تعذر نقل أماكن البصمة.");if(button){button.disabled=false;button.textContent="نقل الأماكن والباركودات الأصلية";}}}

$("#logout-btn").onclick=async()=>{stopSessionSecurity();sessionStorage.removeItem(AUTH_SESSION_MARKER);if(state.demo){state.demo=false;state.bound=false;openAuth();}else await signOut(auth);};
$("#global-search").oninput=e=>{state.search=e.target.value;if(state.page==="employees")renderEmployees();};
$("[data-open-notifications]").onclick=()=>{state.page="notifications";renderNav();renderPage();};
initialize().catch(error=>{$("#loading").innerHTML=`<b>تعذر تشغيل النظام</b><p>${escapeHtml(error.message)}</p>`;});
