// Payroll periods and deduction review; report creation is intentionally separate.
let ctx, subscriptions=[], data={}, waivers={}, detail=null, loadId=0, loadedKey='', clock=null;
const vals=value=>Object.values(value||{}).filter(Boolean);
const keyDate=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export function nextDate(value){const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()+1);return keyDate(d);}
export function monthDate(value,offset=1,day=Number(value.slice(8))){const [y,m]=value.split('-').map(Number),d=new Date(y,m-1+offset,1,12);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return keyDate(d);}
export function resolvePayrollPeriod(config={},today){let start=config.startDate||'',end=config.endDate||'';if(!start||!end)return{start,end,active:false};if(end<today&&!config.fixed)return{start:nextDate(end),end:'',active:false};if(config.fixed){const endDay=config.endDay||Number(end.slice(8));while(end<today){start=nextDate(end);end=monthDate(end,1,endDay);}}return{start,end,endDay:config.endDay||Number(end.slice(8)),active:Boolean(start&&end&&end>=start)};}
export function payrollWindows(period){return[{start:period.start,end:period.end,tone:'red'},{start:nextDate(period.end),end:monthDate(period.end,1,period.endDay),tone:'amber'}];}
const minutes=value=>String(value||'00:00').split(':').map(Number).reduce((h,m)=>h*60+m);
const shiftEnd=(date,assignment)=>{let stamp=Date.parse(`${date}T${assignment.to}:00+03:00`);if(minutes(assignment.to)<=minutes(assignment.from))stamp+=86400000;return stamp;};
function penaltyType(reason=''){const branch=reason.match(/في فرع (.+?)(?: بتاريخ|$)/)?.[1];if(reason.includes('بصمة دخول'))return`بصمة حضور مفقودة${branch?' من فرع '+branch:''}`;if(reason.includes('بصمة خروج'))return`بصمة انصراف مفقودة${branch?' من فرع '+branch:''}`;return reason||'خصم بصمة';}
export function buildPayrollLedger(source,employees,now=Date.now()){
 const records=[],known=new Map(employees.map(e=>[e.id,e]));
 for(const [date,schedule] of Object.entries(source.schedules||{})){
  const assignments=vals(schedule.assignments).filter(a=>a.employeeId&&a.from&&a.to).sort((a,b)=>a.from.localeCompare(b.from));
  for(const employeeId of new Set(assignments.map(a=>a.employeeId))){
   const shifts=assignments.filter(a=>a.employeeId===employeeId),events=vals(source.attendance?.[date]?.[employeeId]).slice();
   for(const p of vals(source.legacy)){if(p.date?.slice(0,10)!==date)continue;const employee=known.get(String(p.empId))||employees.find(e=>e.fullName===p.empName);if(employee?.id!==employeeId)continue;const stamp=Date.parse(p.iso||`${date}T${p.timeExact||p.time||'00:00'}+03:00`);if(stamp)events.push({timestamp:stamp,type:p.type==='out'?'checkOut':'checkIn'});}
   // Match each event to its scheduled time window, retaining orphan checkout punches.
   const buckets=shifts.map(()=>[]);for(const event of events.sort((a,b)=>Number(a.timestamp)-Number(b.timestamp))){const stamp=Number(event.timestamp);const candidates=shifts.map((a,index)=>{const start=Date.parse(`${date}T${a.from}:00+03:00`),end=shiftEnd(date,a),target=event.type==='checkOut'?end:start;return{index,distance:Math.abs(stamp-target),branch:a.branchId};}).filter(c=>!event.branchId||event.branchId===c.branch);const selected=candidates.sort((a,b)=>a.distance-b.distance)[0];if(selected)buckets[selected.index].push(event);}
   shifts.forEach((a,index)=>{const events=buckets[index],checkIn=events.find(e=>e.type==='checkIn'),checkOut=events.filter(e=>e.type==='checkOut').at(-1),branch=({hawalli:'حولي',abu_al_hasaniya:'أبو الحصانية',yarmouk:'اليرموك'})[a.branchId]||a.branchName||a.branchId||'غير محدد',start=Date.parse(`${date}T${a.from}:00+03:00`),end=shiftEnd(date,a),duration=Math.max(0,Math.round((end-start)/60000)-Number(a.breakMinutes||0));let type='',deducted=0;
    if(!checkIn&&!checkOut&&now>=end){type=shifts.length>1?`غياب عن فترة دوام ${branch}`:'غياب';deducted=duration;}
    else if(checkIn){deducted=Math.max(0,Math.floor((Number(checkIn.timestamp)-start)/60000));if(deducted<=10)deducted=0;deducted=Math.min(deducted,duration);if(deducted)type=`تأخير بالحضور في فرع ${branch}`;}
    if(type&&deducted)records.push({id:`time-${date}-${employeeId}-${a.id||`${a.branchId}-${a.from}-${a.to}`}`,employeeId,date,type,minutes:deducted,category:'time',notes:'',from:a.from,to:a.to,branch});
   });
  }
 }
 for(const book of vals(source.books)){if(book.employeeId&&book.date)records.push({id:`book-${book.id}`,employeeId:book.employeeId,date:book.date,type:'كتاب خصم',bookId:book.id,bookNumber:book.bookNumber,amountFils:Math.round(Number(book.amount||0)*1000),category:'amount',sourceReason:book.reason||'',notes:''});}
 for(const [date,items] of Object.entries(source.penalties||{}))for(const [id,p] of Object.entries(items||{})){records.push({id:`penalty-${date}-${id}`,employeeId:p.employeeId,date:p.date||date,type:penaltyType(p.reason),amountFils:Number(p.amountFils??Math.round(Number(p.amount||0)*1000)),category:'amount',sourceReason:p.reason||'',notes:''});}
 return records.sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id));
}
function esc(value){return ctx.escapeHtml(String(value??''));}
export function payrollDay(date){return new Intl.DateTimeFormat('ar-KW',{weekday:'long',timeZone:'Asia/Kuwait'}).format(new Date(`${date}T12:00:00+03:00`));}
export function payrollClock(value){const [hour,minute]=String(value).split(':').map(Number);return`${hour%12||12}:${String(minute).padStart(2,'0')} ${hour<12?'صباحًا':'مساءً'}`;}
function dateText(date){return date?date.split('-').reverse().join(' / '):'—';}
function dateHtml(date){return`<bdi dir="ltr">${dateText(date)}</bdi>`;}
function money(fils){return`${(Number(fils||0)/1000).toFixed(3)} د.ك`;}
function timeText(value){return`${Math.floor(value/60)} ساعة ${value%60} دقيقة`;}
function period(){return resolvePayrollPeriod(ctx.state.settings.payrollPeriod,ctx.today());}
function warning(){return'<div class="payroll-warning" role="status">يرجى تحديد فترة بيانات تقرير الرواتب</div>';}
function heading(title,subtitle,extra=''){return`<div class="payroll-heading"><div><span>${esc(subtitle)}</span><h1>${esc(title)}</h1></div><div>${extra}<button class="secondary payroll-settings" title="تحديد الفترة لبيانات تقرير الرواتب" aria-label="إعدادات فترة تقرير الرواتب">⚙</button></div></div>`;}
function bindSettings(){document.querySelectorAll('.payroll-settings').forEach(b=>b.onclick=openPeriodSettings);}
function modal(title,body,footer){const root=document.querySelector('#modal-root');root.innerHTML=`<div class="modal-backdrop payroll-backdrop"><section class="modal payroll-modal" role="dialog" aria-modal="true" aria-labelledby="payroll-modal-title"><header><h3 id="payroll-modal-title">${esc(title)}</h3><button class="modal-close" aria-label="إغلاق">×</button></header><div class="payroll-modal-body">${body}<p class="payroll-error" role="alert"></p></div><footer>${footer}</footer></section></div>`;const close=()=>root.innerHTML='';root.querySelector('.modal-close').onclick=close;root.querySelector('[data-cancel]').onclick=close;root.querySelector('.modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)close();};return{root,close};}
function openPeriodSettings(){const p=period(),saved=ctx.state.settings.payrollPeriod||{},m=modal('تحديد الفترة لبيانات تقرير الرواتب',`<div class="payroll-date-inputs"><label>من تاريخ<input id="payroll-start" type="date" value="${esc(p.start)}"></label><label>إلى تاريخ<input id="payroll-end" type="date" value="${esc(p.end)}"></label></div><label class="payroll-pin"><input type="checkbox" id="payroll-fixed" ${saved.fixed?'checked':''}> تثبيت</label><small>تتجدد الفترة شهريًا عند التثبيت، وتبدأ الفترة الجديدة في اليوم التالي لنهاية السابقة.</small>`,'<button class="secondary" data-cancel>إلغاء</button><button class="primary" id="payroll-save">حفظ</button>');m.root.querySelector('#payroll-save').onclick=async e=>{const start=m.root.querySelector('#payroll-start').value,end=m.root.querySelector('#payroll-end').value,fixed=m.root.querySelector('#payroll-fixed').checked,error=m.root.querySelector('.payroll-error');if(!start||!end||end<start){error.textContent='يرجى تحديد تاريخين صحيحين؛ تاريخ النهاية لا يسبق البداية.';return;}if(end<ctx.today()){error.textContent='يرجى تحديد فترة لم تنتهِ بعد.';return;}e.currentTarget.disabled=true;try{const config={startDate:start,endDate:end,fixed,endDay:Number(end.slice(8)),updatedAt:Date.now()};await ctx.save('settings/payrollPeriod',config);ctx.state.settings.payrollPeriod=config;detail=null;loadedKey='';m.close();renderCurrent();ctx.toast('تم حفظ فترة تقرير الرواتب');}catch(err){error.textContent=err.message||'تعذر حفظ الفترة';e.target.disabled=false;}};}
function reportPage(){const p=period();ctx.container.innerHTML=`<section class="payroll-page">${heading('تقرير الرواتب','بيانات تقارير الرواتب')}${p.active?`<h2 class="payroll-period-title">تقرير الرواتب من ${dateHtml(p.start)} إلى ${dateHtml(p.end)}</h2>`:warning()}<div class="payroll-table-wrap"><table class="payroll-table"><thead><tr>${['رقم التقرير','عدد الموظفين','عدد الصفحات','من تاريخ','إلى تاريخ','إجراءات'].map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody><tr><td colspan="6" class="payroll-empty">لا توجد تقارير رواتب</td></tr></tbody></table></div></section>`;bindSettings();}
function rowsFor(employeeId,window,category){return(data.records||[]).filter(r=>r.employeeId===employeeId&&r.date>=window.start&&r.date<=window.end&&(!category||r.category===category));}
function dueRows(rows){return rows.filter(r=>!waivers[r.id]);}
function employeePage(){const p=period();if(!p.active){ctx.container.innerHTML=`<section class="payroll-page">${heading('الخصومات','خصومات الموظفين')}${warning()}</section>`;bindSettings();return;}const windows=payrollWindows(p);ctx.container.innerHTML=`<section class="payroll-page">${heading('الخصومات','خصومات الموظفين')}<h2 class="payroll-period-title">من ${dateHtml(p.start)} إلى ${dateHtml(p.end)}</h2><div id="payroll-data-status"></div><div class="payroll-employees">${ctx.state.employees.map(e=>`<article class="payroll-employee"><header><span class="payroll-avatar">${ctx.photo(e)?`<img src="${esc(ctx.photo(e))}" alt="">`:esc(ctx.initials(e.fullName))}</span><div><h3>${esc(e.fullName)}</h3><small>${esc(e.jobTitle||'')}</small></div></header>${windows.map((w,index)=>{const rows=dueRows(rowsFor(e.id,w)),sum=rows.reduce((n,r)=>n+(r.amountFils||0),0),time=rows.reduce((n,r)=>n+(r.minutes||0),0);return`<section class="payroll-bucket ${w.tone}"><h4>خصومات من راتب شهر ${Number(w.end.slice(5,7))} / ${w.end.slice(0,4)}</h4><div><button data-payroll-employee="${esc(e.id)}" data-window="${index}" data-category="amount"><span>مبلغ</span><b>${money(sum)}</b></button><button data-payroll-employee="${esc(e.id)}" data-window="${index}" data-category="time"><span>تأخير وغياب</span><b>${timeText(time)}</b></button></div></section>`;}).join('')}</article>`).join('')}</div></section>`;bindSettings();document.querySelectorAll('[data-payroll-employee]').forEach(b=>b.onclick=()=>{detail={employeeId:b.dataset.payrollEmployee,window:Number(b.dataset.window),category:b.dataset.category};renderCurrent();});}
function notesFor(row){return waivers[row.id]?`سبب الإعفاء: ${waivers[row.id].reason}`:row.notes||'—';}
function detailTable(rows,exporting=false,offset=0){const timed=detail.category==='time';return`<table class="payroll-table"><thead><tr>${['م','اليوم','التاريخ',timed?'نوع الحالة':'نوع الخصم',timed?'الوقت المخصوم':'المبلغ المخصوم',timed?'حالة الفترة':'حالة الخصم','ملاحظات',...(!exporting?['إجراءات']:[])].map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${offset+i+1}</td><td>${esc(payrollDay(r.date))}</td><td>${dateHtml(r.date)}</td><td>${esc(r.type)}${r.bookNumber?`<br>${exporting?esc(r.bookNumber):`<button class="payroll-book" data-book="${esc(r.bookId)}">${esc(r.bookNumber)}</button>`}`:''}${r.from?`<small>${esc(r.branch)} · ${payrollClock(r.from)} — ${payrollClock(r.to)}</small>`:''}</td><td>${timed?timeText(r.minutes):money(r.amountFils)}</td><td class="${waivers[r.id]?'payroll-exempt':'payroll-due'}">${waivers[r.id]?'معفى':'مستحق'}</td><td>${esc(notesFor(r))}</td>${exporting?'':`<td>${waivers[r.id]?'—':`<button class="secondary" data-exempt="${esc(r.id)}">إعفاء</button>`}</td>`}</tr>`).join('')||`<tr><td colspan="${exporting?7:8}" class="payroll-empty">لا توجد خصومات ضمن الفترة المحددة</td></tr>`}</tbody></table>`;}
function detailPage(){const p=period();if(!p.active){detail=null;return employeePage();}const e=ctx.state.employees.find(e=>e.id===detail.employeeId);if(!e){detail=null;return employeePage();}const w=payrollWindows(p)[detail.window],rows=rowsFor(e.id,w,detail.category);ctx.container.innerHTML=`<section class="payroll-page">${heading(detail.category==='time'?'تفاصيل التأخير والغياب':'تفاصيل الخصومات',e.fullName,'<button class="secondary" id="payroll-back">→ رجوع</button>')}<div class="payroll-detail-bar"><b>من ${dateHtml(w.start)} إلى ${dateHtml(w.end)}</b><div><button class="secondary" id="payroll-excel">تحميل Excel</button><button class="primary" id="payroll-pdf">تحميل PDF</button></div></div><div class="payroll-table-wrap">${detailTable(rows)}</div></section>`;bindSettings();document.querySelector('#payroll-back').onclick=()=>{detail=null;renderCurrent();};document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>ctx.showBook(b.dataset.book));document.querySelectorAll('[data-exempt]').forEach(b=>b.onclick=()=>openExemption(rows.find(r=>r.id===b.dataset.exempt),e));document.querySelector('#payroll-excel').onclick=()=>exportExcel(rows,e,w);document.querySelector('#payroll-pdf').onclick=()=>exportPdf(rows,e,w);}
function openExemption(row,employee){const m=modal('إعفاء من الخصم',`<dl class="payroll-exempt-details"><dt>الموظف</dt><dd>${esc(employee.fullName)}</dd><dt>النوع</dt><dd>${esc(row.type)} ${esc(row.bookNumber||'')}</dd><dt>التاريخ</dt><dd>${dateHtml(row.date)}</dd>${row.from?`<dt>فترة الدوام</dt><dd>${esc(row.branch)} · ${payrollClock(row.from)} — ${payrollClock(row.to)}</dd>`:''}<dt>${row.category==='time'?'الوقت المخصوم':'المبلغ المخصوم'}</dt><dd>${row.category==='time'?timeText(row.minutes):money(row.amountFils)}</dd><dt>التفاصيل</dt><dd>${esc(row.sourceReason||row.notes||row.branch||'—')}</dd></dl><label>سبب الإعفاء<textarea id="payroll-exempt-reason" rows="3"></textarea></label>`,'<button class="secondary" data-cancel>إلغاء</button><button class="primary" id="payroll-exempt-approve" disabled>اعتماد</button>'),reason=m.root.querySelector('textarea'),approve=m.root.querySelector('#payroll-exempt-approve');reason.oninput=()=>approve.disabled=!reason.value.trim();approve.onclick=async()=>{approve.disabled=true;try{const value={reason:reason.value.trim(),employeeId:row.employeeId,sourceId:row.id,date:row.date,category:row.category,approvedAt:Date.now(),approvedBy:ctx.state.user?.uid||'demo'};await ctx.save(`payrollExemptions/${row.id}`,value);waivers[row.id]=value;m.close();renderCurrent();ctx.toast('تم اعتماد الإعفاء');}catch(err){m.root.querySelector('.payroll-error').textContent=err.message||'تعذر اعتماد الإعفاء';approve.disabled=false;}};reason.focus();}
function exportExcel(rows,employee,w){if(!window.XLSX)return ctx.toast('تعذر تحميل مكتبة Excel');const timed=detail.category==='time',values=rows.map((r,i)=>({'م':i+1,'اليوم':payrollDay(r.date),'التاريخ':dateText(r.date),[timed?'نوع الحالة':'نوع الخصم']:`${r.type}${r.bookNumber?' '+r.bookNumber:''}`,[timed?'الوقت المخصوم':'المبلغ المخصوم']:timed?timeText(r.minutes):money(r.amountFils),[timed?'حالة الفترة':'حالة الخصم']:waivers[r.id]?'معفى':'مستحق','ملاحظات':notesFor(r)}));const workbook=window.XLSX.utils.book_new(),sheet=window.XLSX.utils.json_to_sheet(values.length?values:[{'م':'','اليوم':'','التاريخ':'',[timed?'نوع الحالة':'نوع الخصم']:'لا توجد خصومات',[timed?'الوقت المخصوم':'المبلغ المخصوم']:'',[timed?'حالة الفترة':'حالة الخصم']:'','ملاحظات':''}]);sheet['!cols']=[{wch:6},{wch:14},{wch:18},{wch:55},{wch:25},{wch:18},{wch:65}];sheet['!views']=[{rightToLeft:true}];window.XLSX.utils.book_append_sheet(workbook,sheet,'الخصومات');window.XLSX.writeFile(workbook,`${employee.fullName} ${w.start} - ${w.end}.xlsx`);}
async function exportPdf(rows,employee,w){if(!window.html2canvas||!window.jspdf)return ctx.toast('تعذر تحميل مكتبة PDF');const root=document.createElement('div');root.className='payroll-pdf';root.dir='rtl';document.body.append(root);try{const pdf=new window.jspdf.jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true}),pages=Math.max(1,Math.ceil(rows.length/6));for(let page=0;page<pages;page++){root.innerHTML=`<h1>${detail.category==='time'?'تفاصيل التأخير والغياب':'تفاصيل الخصومات'}</h1><h2>${esc(employee.fullName)}</h2><p>من ${dateHtml(w.start)} إلى ${dateHtml(w.end)}</p>${detailTable(rows.slice(page*6,(page+1)*6),true,page*6)}<footer>صفحة ${page+1} / ${pages}</footer>`;const canvas=await window.html2canvas(root,{scale:2,backgroundColor:'#fff',useCORS:true});if(page)pdf.addPage();const width=Math.min(281,194*canvas.width/canvas.height),height=canvas.height*width/canvas.width;pdf.addImage(canvas.toDataURL('image/jpeg',0.92),'JPEG',(297-width)/2,8,width,height);}pdf.save(`${employee.fullName} ${w.start} - ${w.end}.pdf`);}catch(err){ctx.toast('تعذر تجهيز PDF: '+err.message);}finally{root.remove();}}
function stopSubscriptions(){subscriptions.forEach(unsubscribe=>unsubscribe());subscriptions=[];}
function renderCurrent(){if(!ctx||!['payroll','salary-deductions'].includes(ctx.state.page))return;if(ctx.state.page==='payroll')reportPage();else{if(detail)detailPage();else employeePage();loadData();}}
function loadData(){const p=period();if(!p.active){stopSubscriptions();loadedKey='';return;}const windows=payrollWindows(p),key=`${p.start}:${windows[1].end}`;if(key===loadedKey)return;stopSubscriptions();loadedKey=key;const request=++loadId;data={records:[],books:ctx.state.deductions};const received=new Set();const status=()=>{const el=document.querySelector('#payroll-data-status');if(el)el.textContent=received.size<5?'جارٍ تحميل بيانات الخصومات...':'';document.querySelectorAll('[data-payroll-employee],#payroll-excel,#payroll-pdf,[data-exempt]').forEach(button=>button.disabled=received.size<5);};status();for(const [name,path,legacy] of [['schedules','schedules'],['attendance','attendance'],['penalties','attendanceDeductions'],['legacy','fingerprintPunches',true],['exemptions','payrollExemptions']]){const range=name==='exemptions'?null:{start:p.start,end:windows[1].end,legacy};subscriptions.push(ctx.watch(path,range,value=>{if(request!==loadId)return;data[name]=value||{};received.add(name);if(name==='exemptions')waivers=data.exemptions;data.books=ctx.state.deductions;data.records=buildPayrollLedger(data,ctx.state.employees);if(detail)detailPage();else employeePage();status();},error=>{loadedKey='';const el=document.querySelector('#payroll-data-status');if(el){el.className='payroll-error';el.textContent='تعذر جلب بيانات الخصومات: '+error.message;}}));}}
export function renderPayroll(context){ctx=context;if(!clock)clock=setInterval(()=>{if(['payroll','salary-deductions'].includes(ctx.state.page)){const p=period();if(!p.active||`${p.start}:${monthDate(p.end,1,p.endDay)}`!==loadedKey){loadedKey='';detail=null;renderCurrent();}else if(ctx.state.page==='salary-deductions'){data.records=buildPayrollLedger(data,ctx.state.employees);if(detail)detailPage();else employeePage();}}else{stopSubscriptions();loadedKey='';}},60000);renderCurrent();}
export function refreshPayroll(){if(!ctx)return;loadedKey='';renderCurrent();}
